Kong/deck

- cmd/root.go
@hbagdi thanks a lot for building deck! The logic for http headers was already implemented by you, though the cmd wasn't setup to accept them. Please review. Thank you!
> added cmd flags for http headers

- file/builder.go
- file/builder_test.go
> fix(file) correctly parse routes and plugins for routes

- dump/dump.go
Linked issue: https://github.com/hbagdi/deck/issues/119
> Exclude consumer plugins when --skip-consumers is on

- solver/solver.go
#127 
Typo in registering ca_certificate kind
> Fixed typo in registering ca_certificate in CRUD registry

- examples/deck.yml
> docs: document a sample deck.yml file

- utils/types.go
- utils/types_test.go
> fix: remove trailing slashes to sanitize --kong-addr input

- diff/basicAuth.go
> fix(diff) update basic-auth warning to communicate the issue

- cmd/analytics.go
there will panic nil point err
> fix: will panic on sendAnalytics faild

- diff/diff.go
Background
----------
Syncer works with a single producer, multiple consumers with a queue in
between them which has a constant buffer size of 10:
`const eventBuffer = 10`
Each time the producer ATTEMPTS to add an item into queue, inflightOps
is incremented atomically unconditionally inside queueEvent().
A consumer decrements the counter once it processes an event, no matter
the event was processed successfully or failed.
A consumer's thread (goroutine) exits once the event channel is closed.
This channel is closed by the producer when the producer is done.
Problem
-------
There are two problems:
1. If a producer's queue is full and `stopChan` is closed,
`queueEvent()` incorrectly increments inflightOps and returns an error,
which causes the producer to exit and eventually all consumers …
> fix(sync) resolve concurrenct wait bug

- CHANGELOG.md
> docs(changelog) document changes for v1.2.2

- CHANGELOG.md
Write up changelog for 1.2.4 and fix the 1.2.3 link.
> Document changes for v1.2.4

- file/builder_test.go
- file/schema.go
- go.mod
- go.sum
- chore: update go-kong to v0.15.0
- feat: add req/resp buffering options to schema
- chore: update tests for req/resp buffering
fixes https://github.com/Kong/deck/issues/260
> feat: add request and response buffering options

- .github/workflows/test.yaml
- Makefile
Also updates github actions to use the Makefile
Fix #277
> chore: add a basic Makefile for the project

- cmd/common.go
- cmd/dump.go
- cmd/konnect_dump.go
- cmd/reset.go
- cmd/utils.go
- file/writer.go
- file/writer_test.go
- utils/utils.go
- utils/utils_test.go
> feat(cmd) ask confirmation from user before overwriting a file

- .github/dependabot.yml
Configure github-actions update with dependabot
> Keep actions up to date with Dependabot

- .github/workflows/test.yaml
- Makefile
- README.md
> Add codecov , codecov badge and Go Report Card badge

- dump/dump.go
> feat(dump) apply select-tags to credetentials

- cmd/konnect_dump.go
> fix(dump) use konnect filename for konnect dump

- cmd/common_konnect.go
- cmd/konnect_dump.go
- utils/types.go
This reverts commit 1a38c64a1bdc634ef8cc2b68d0e26296986f1f42.
> Revert "Revert "feat: add sane default timeouts to http.Client""

- file/types.go
- file/types_test.go
- file/writer.go
- file/writer_test.go
> Sort FServiceVersion by Version first and by ID by default

- .gitignore
- Makefile
- cmd/root.go
- docs/generate-docs.go
- go.sum
> docs: implement machinery to generate CLI reference docs

- print/color.go
- This packages refactors code in the print package to DRY the code out
- It also introduces a way to silence output (prep for #152)
> feat(print) refactor and introduce DisableOutput

- cmd/common_konnect.go
- cmd/konnect_dump.go
- cmd/konnect_ping.go
- cmd/root.go
- konnect/client.go
- konnect/login_service.go
- utils/types.go
> feat: configurable value of konnect API endpoint

- diff/diff.go
- file/builder.go
- konnect/types.go
- reset/reset.go
- state/credentials.go
- utils/defaulter.go
Some are outdated, some have already been completed, some have issues for them already.
> chore: clean up TODOs

- .golangci.yml
- konnect/document_service.go
Follow-up to https://github.com/Kong/deck/pull/400 to take care of the comments from @mmorel-35
> Enable more linters: follow-up

- go.mod
- go.sum
- utils/uuid.go
Following our [discussion](https://github.com/Kong/deck/pull/424#discussion_r641769045)
> Use github.com/google/uuid to generate uuid V4

- .golangci.yml
- konnect/control_plane_relations_service.go
- konnect/document_service.go
- konnect/login_service.go
- konnect/service_version_service.go
- state/indexers/md5Indexer_test.go
- state/indexers/subFieldIndexer_test.go
The bodyclose linter is going off incorrectly. The body is actually
closed before returning so we are disabling the linter.
> chore: bump up linter, more linters, conditionally skip bodyclose

- file/validate.go
> Revert "prevent user overwrite default configuration"

- diff/diff.go
- types/core.go
> refactor: introduce EntityType for entity definitions

- .github/dependabot.yml
- .github/workflows/test.yaml
- Dockerfile
This also includes the update of codecov-action and alpine
> Support docker with Dependabot 

- cmd/convert.go
- cmd/diff.go
- cmd/dump.go
- cmd/konnect.go
- cmd/konnect_diff.go
- cmd/konnect_dump.go
- cmd/konnect_ping.go
- cmd/konnect_sync.go
- cmd/ping.go
- cmd/reset.go
- cmd/root.go
- cmd/sync.go
- cmd/validate.go
- cmd/version.go
@hbagdi @lena-larionova 
* Update CLI command descriptions
Address: https://konghq.atlassian.net/browse/DOCU-1666
Create clearer docs. 
Compile code and check the `--help` command.
> [DOCU-1666] Documentation: Update decK CLI command descriptions

- README.md
Signed-off-by: John Harris <john.harris@konghq.com>
> docs: Add Windows install instructions.

- cmd/root.go
This PR allows users to specify a CA cert bundle from a file. The
existing `--ca-cert` flag takes precedence over this new option.
Signed-off-by: John Harris <john.harris@konghq.com>
> feat: ability to specify CA cert from file

- .goreleaser.yml
- CHANGELOG.md
- cmd/common.go
1.8.2 bundles an RBAC permissions fix and build target change.
Fix #495
Fix #478
> Release 1.8.2

- CHANGELOG.md
Added 1.10.0 change instructions
> docs(*) add 1.10.0 changes

- file/readfile.go
- file/readfile_test.go
- file/testdata/badyamlwithspace/bar.yml
https://github.com/Kong/deck/issues/578
> fix: malformed YAML results in empty config set

- go.mod
- go.sum
Related PR: https://github.com/Kong/gojsondiff/pull/1
Related issue: https://github.com/Kong/deck/issues/538
> chore(deps): update gojsondiff

- CHANGELOG.md
Adds 1.13.0 with changes since 1.12.4.
> chore: add changelog for 1.13.0

- file/builder_test.go
- utils/constants.go
- utils/defaulter_test.go
solves https://github.com/Kong/deck/issues/655
> feat: allow setting defaults for services' host and port

- .github/workflows/integration-enterprise-nightly.yaml
Require access to the nightly image credentials to test against it.
> chore: make nightly image tests conditional

- diff/diff.go
when using deck as a lib, if we want to capture the operations logs (creations, updates, deletions), we need to reconfigure the global vars in the `cprint` package. this is an issue if we want to do different deck operations in parallel.
this change introduce new parameters to the Syncer, to configure custom printer funcs, without depending on the `cprint` package. Note that by default if no custom printer funcs are configured, the ones from the `cprint` package will be used - so no behaviour change.
> refactor(diff): allow custom printer funcs

- .golangci.yml
- file/readfile.go
- file/types_test.go
- file/validate.go
- file/writer.go
- go.mod
- go.sum
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> chore(deps): use only sigs.k8s.io/yaml to handle yaml

- .github/workflows/release.yaml
> feat: build and release for arm platform

- .golangci.yml
Similar to https://github.com/Kong/go-kong/pull/337
> chore(linters) update depguard config

- cmd/file_addplugins.go
- cmd/file_addtags.go
- cmd/file_listtags.go
- cmd/file_merge.go
- cmd/file_openapi2kong.go
- cmd/file_patch.go
- cmd/file_removetags.go
- go.mod
- go.sum
fixes case sensitive file formats (yaml/json)
> chore(deps): bump go-apiops to 0.1.18

- RELEASE.md
adds a link to the release job
> chore(release): update release instructions

- CHANGELOG.md
- konnect/login_service.go
- konnect/login_service_test.go
- tests/integration/sync_test.go
- tests/integration/testdata/sync/014-update-consumer-with-custom-id/kong3x-initial.yaml
- tests/integration/testdata/sync/014-update-consumer-with-custom-id/kong3x.yaml
* Add support for konnect AU region
* bump changelog to 1.29.0
> feat: add support for konnect AU region

- Dockerfile
> fix: fix docker builds for arch != amd64

- cmd/common.go
- cmd/gateway_validate.go
- go.mod
- go.sum
- tests/integration/sync_test.go
- tests/integration/testdata/sync/030-lookup-tags-routes/global_routes.yaml
- tests/integration/testdata/sync/030-lookup-tags-routes/plugins_and_routes.yaml
- tests/integration/testdata/sync/030-lookup-tags-routes/plugins_lookup.yaml
- tests/integration/testdata/sync/030-lookup-tags-routes/plugins_no_lookup.yaml
Requires https://github.com/Kong/go-database-reconciler/pull/44
> feat: add default_lookup_tags support for routes

- README.md
- RELEASE.md
> fix(docs): update install and release instructions

- go.mod
- go.sum
- tests/integration/diff_test.go
- tests/integration/testdata/diff/004-no-diff-plugin/kong.yaml
Ref: https://github.com/Kong/go-database-reconciler/pull/93
> fix: correct plugins config comparison

- CHANGELOG.md
- go.mod
- go.sum
I have added all changelog updates together here.
> chore: bumped up go-kong and added changelog updates

- kong2kic/global_plugin.go
- kong2kic/kong2kic.go
- kong2kic/route.go
- kong2kic/service.go
- kong2kic/testdata/route-gw-v2-output-expected.yaml
- kong2kic/testdata/route-gw-v3-output-expected.yaml
- kong2kic/testdata/route-ingress-output-expected.yaml
- kong2kic/testdata/route-input.yaml
- kong2kic/testdata/service-input.yaml
- kong2kic/testdata/service-output-expected.yaml
- kong2kic/utils.go
Correctly process top level definitions of plugins and routes. Previously, top level definitions of plugins and routes were not processed.
> fix: process top-level plugins and routes

- CHANGELOG.md
- README.md
Fixes https://github.com/Kong/deck/issues/1543
go-database-reconciler diff: https://github.com/Kong/go-database-reconciler/compare/v1.22.0...v1.22.1
go-kong diff: https://github.com/Kong/go-kong/compare/v0.64.1...v0.65.0
> chore: add changelog for v1.46.1

- tests/integration/testdata/diff/004-no-diff-plugin/initial-ip-restriction.yaml
- tests/integration/testdata/diff/004-no-diff-plugin/protocol-initial-order-plugins.yaml
- tests/integration/testdata/diff/004-no-diff-plugin/protocol-reordered-plugins.yaml
Summary
Update the examples to use mock values
> fix: update example for ip-restriction for plugin

- tests/integration/sync_test.go
Reverts Kong/deck#1586
Ref: https://kongstrong.slack.com/archives/C0663589T3R/p1744032807743669?thread_ts=1744026647.277419&cid=C0663589T3R
> Revert "fix: tests failing due to missing timeout key"

- convert/convert.go
- convert/pluginUpdates.go
- convert/routeUpdates.go
- convert/utils.go
Required for: https://github.com/Kong/deck/issues/1554
This PR structures the convert command utilities in their specific files.
> refactor: refactor necessary for migration utility

- tests/integration/sync_test.go
Validated the test fix from the test run here: https://github.com/Kong/deck/actions/runs/15773343102/job/44462266139
> tests: fixed vault sync test for 3.11

- go.mod
- go.sum
- tests/integration/sync_test.go
- tests/integration/testdata/sync/043-keys-and-key_sets/kong-name-update.yaml
- tests/integration/testdata/sync/043-keys-and-key_sets/kong-no-name-konnect.yaml
- tests/integration/testdata/sync/043-keys-and-key_sets/kong-no-name.yaml
For https://github.com/Kong/go-database-reconciler/issues/300
> fix: keys keysets creation without names

- go.mod
- go.sum
Fixes https://github.com/Kong/deck/issues/1693
PR on go-apiops: https://github.com/Kong/go-apiops/pull/274
> chore: bump go-apiops to fix panic in o2k

- kong2tf/builder.go
- kong2tf/builder_default_terraform.go
- kong2tf/generate_resource.go
- kong2tf/kong2tf_test.go
- kong2tf/testdata/partial-input.yaml
- kong2tf/testdata/partial-output-expected.tf
Modelled on https://github.com/Kong/terraform-provider-konnect/blob/main/examples/resources/gateway_partial.tf#L1-L20
> Add Partial support to kong2tf

- cmd/common_konnect.go
- cmd/gateway_dump.go
- go.mod
- go.sum
- sanitize/exempts.go
- sanitize/sanitize.go
- sanitize/sanitize_test.go
- sanitize/utils.go
Merging the temporary branch back to main as we have the approval from the customer now.
All the code below is already reviewed in the following PRs:
- https://github.com/Kong/deck/pull/1701
- https://github.com/Kong/deck/pull/1709
- https://github.com/Kong/deck/pull/1710
- https://github.com/Kong/deck/pull/1711
- https://github.com/Kong/deck/pull/1718
> feat: deck dump sanitization
