Kong/deck

dump/dump.go

Hi @hbagdi,
Found a bug when trying to sync APIs on a Kong instance with more than 1,000 consumers.  `deck` seem to have got into an infinite loop when dumping the consumers, fetching the first page of 1,000 consumers over and over again.  I suspect that the issue was the `opt` variable being shadowed within the for loops.
Please take a look at this PR which fixes this for consumers, and should also fix it for the other entities (although I have not tested them).  Please let me know what you think.
Thanks for the tool.  It's been very helpful to us.
Regards,
Leon

Fixed infinite loop when fetching multiple pages of consumers exist

---

solver/kong/plugin.go
solver/kong/route.go

@hbagdi Updating a plugin works when a plugin is set for a `route`, but when set for a `service` it fails, basically because of the following:
**Bad Request**: `PUT /plugins/<id> {..., service: {id: <service-id>, <everything else from service>}} // full service struct included`
```json
{
"message": "schema violation (protocols: must match the protocols of at least one route pointing to this Plugin's service)",
"name": "schema violation",
"fields": {
"protocols": "must match the protocols of at least one route pointing to this Plugin's service"
},
"code": 2
}
```
**This works**: `PUT /plugins/<id> {..., service: {id: <service-id>}} // only service.id included`
Creating a new `service` with only the ID and assigning it to the `plugin` before calling `s.client.Plugins.Create(nil, …

using only service.id when updating a plugin

---

solver/kong/plugin.go

Kong 1.1 introduces a change where specifying the name and id of the
service on a POST request results in an incorrect error from Kong.
While, this is a bug in Kong, Kong doesn't promise any compat for cases
when Admin API reqeusts contains entire nested foreign objects.

fix(solver) set foreign ID only for plugins PUT requests

---

cmd/diff.go
cmd/dump.go
cmd/reset.go
cmd/sync.go
counter/counter.go
counter/counter_test.go
dump/dump.go
file/reader.go
file/reader_test.go
file/types.go
file/writer.go
file/writer_test.go
kong.yaml
utils/tags.go
utils/tags_test.go

Entities in Kong's DB can be managed using multiple configuration file.
Each file can have a `select-tag` which can be used to shard entities in Kong.
To ease on-boarding, users can create different state file using the `dump` command, which can export only a subset of all Kong entities, which are sharing a (set of) common tags.

feat: add support for tag based config mgmt

---

utils/constants.go
utils/defaulter_test.go

Breaking change:
This is a limitation of how we fill in default values for the missing
values. It is not possible in Go to determine if a value is nil vs a
zero vaule (false for boolean).
Fixes #18

fix(default) allow strip_path to be set to false

---

Dockerfile

Current Dockerfile builds under `/deck` directory the `deck` binary, then adds the full directory with all source code to the image, then calls deck inside that directory.
The proposed change does the following:
- upgrade to latest `alpine` image, currently 3.10
- copies only the `deck` binary into the final image at `/usr/local/bin` so it can be in the `PATH`
- uses just `deck` as the entrypoint since it's in the `PATH`

Dockerfile - add decK to path

---

dump/dump.go

CACertificate core entitiy was not present in the past
and the Admin API request will error with 404 Not Found for older
versions of Kong.
If we do get a 404 from Kong, instead of erroring out,
return back an empty array of
CACertificates, effectively disabling the entity for versions
which don't have it.
A better solution would be to have a version check, and based
on the version, the entities are loaded and synced.
Fix #59

fix(dump) fix compatibility for Kong < 1.3

---

dump/dump.go

Credentials in Kong are not tagged at the moment.
This leads to an error condition when only a subset where all credentials
If `select_tags` functionality is used, only a subset of consumers
are loaded in memory and this leads to a case where a credential could
belong to a consumer that is not part of the sub-set.
Such ErrNotFound errors are now ignored, if the select_tags feature is
being used.
The duplication of code here is absolutely shit.
Fix #65

fix(dump) ignore credentials for consumers not in the sub-set

---

cmd/dump.go
file/reader.go
file/readfile.go
file/readfile_test.go
file/testdata/badjson/foo.json
file/testdata/file.json
file/testdata/valid/consumers.json
file/types.go
file/writer.go
file/writer_test.go

decK can now export Kong's configuration in JSON format, in addition to
the YAML format.
This can be configured using `--format` flag on the `dump` command.
Input can also be JSON.
Fix #35

feat(file) implement JSON file reader/writer

---

state/aclgroup.go
state/aclgroup_test.go
state/basicauth.go
state/basicauth_test.go
state/cacert.go
state/cacert_test.go
state/certificate.go
state/certificate_test.go
state/consumer.go
state/consumer_test.go
state/hmacauth.go
state/hmacauth_test.go
state/jwtauth.go
state/jwtauth_test.go
state/keyauth.go
state/keyauth_test.go
state/oauth2.go
state/oauth2_test.go
state/plugin.go
state/plugin_test.go
state/route.go
state/route_test.go
state/service.go
state/service_test.go
state/state.go
state/state_test.go
state/target.go
state/target_test.go
state/upstream.go
state/upstream_test.go

This also reduces GC pressure happening due to multiple
memdbs.
In future, transactions across multiple tables can be performed as well.

refactor(state) consolidate multiple memdbs into a single one

---

file/codegen/main.go
file/schema.go
file/types.go
file/types_test.go
kong.yaml

Kong's format requires SNIs to be `name: foo.example.com`.
This is a breaking change for decK.
decK aims to be compatible with Kong's configuration format.
Fix #76
Update #56

fix(file) encode sni with name for compat with Kong's format

---

cmd/common.go

semver lib errors out if no patch is found.
Switch to ParseTolerant() which injects a `0` patch number.
Fix #117

fix: correctly parse Kong's version

---

dump/dump.go

Though these auth plugins are bundled in Kong, it is possible that a
user disabled them. If so, decK throws an error as it receives a HTTP
404 from the Admin API.
decK will now ignore those entities which are disabled in Kong.

fix(dump) do not error out if plugin entity endpoints are disabled

---

cmd/common.go
cmd/diff.go
cmd/sync.go
cmd/validate.go
docs/guides/multi-file-state.md
file/reader.go
file/reader_test.go
file/readfile.go
file/readfile_test.go

I have different state-directories for each environment (ex: production, staging)
And I want to have common configuration for both environments, 
so I could create a symlink for a **common** directory inside each environment directory.
(ex: production/common -> ../common)
Currently, deck-cli state flag (--state) supports only one argument that can be a file or directory.
As [filepath.Walk](https://github.com/hbagdi/deck/blob/0da5af91305f118ea1ab9aae6955628a8b4f7427/file/readfile.go#L102) does [not follow symlinks](https://golang.org/src/path/filepath/path.go?s=12220:12265#L400), deck will ignore symlinks found in the state directory.
Supporting multiple arguments in state flag, we could load multiple state from different locations, as:
```
deck diff -s common -s production
or 
deck diff …
```

feat(state) support multiple files in args

---

cmd/common.go
cmd/diff.go
cmd/dump.go
cmd/ping.go
cmd/reset.go
cmd/sync.go
cmd/validate.go
cmd/version.go

@hbagdi let me know if this is what you meant to achieve for this feature.
I considered an alternative: `Args: cobra.NoArgs` but it gives a generic error. That's why I used custom validator approach to customize error message

feature: #113 invalid postional args

---

file/codegen/main.go
file/schema.go

The validation logic sometimes does not catch missing required fields, resulting in a panic. This updates the schema generation to fix it.
E.g. the following config:
```yaml
services:
- host: httpbin.org
#name: service
routes:
- headers:
my-header:
- httpbin.org
#name: route
plugins:
- name: key-auth
consumers:
- keyauth_credentials:
- key: foo
#username: consumer
upstreams:
- hash_on: none
#name: upstream
```
will cause segfaults like the following for any of the commented out lines above:
```ShellSession
$ deck diff -s kong.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x141b947]
goroutine 7 [running]:
github.com/hbagdi/deck/file.(*stateBuilder).services(0xc0003cfb28) …
```

fix: Missing required fields cause panic

---

cmd/dump.go
cmd/reset.go

In `dump` and `reset` commands, checks if a specified workspace exists before trying to work with it. This makes sure the error message accurately reflects what the problem is.
E.g. right now:
```ShellSession
$ deck dump -w Demo
Error: reading configuration from Kong: snis: Not found
```
After this PR:
```ShellSession
$ deck dump -w Demo
Error: checking workspace 'Demo' in Kong: Not found
```
Uses the same code as is already in place for `sync` and `diff`.

fix(dump+reset): Check if workspace exists

---

cmd/root.go

Ignores a missing `.deck` file by adding code as recommended in https://github.com/spf13/viper/blob/master/README.md.
Fixes https://github.com/hbagdi/deck/issues/151.

fix(config) Ignore missing config file

---

file/types.go
file/types_test.go

Populate port according to the protocol scheme in the `url` sugar
attribute. Default port of `80` is now populated to match Kong's
behavior in the same case.

fix(file) populate port according to protocol in url

---

cmd/root.go

Fixing some minor typos that were present on the help command: 
deck --help

Fixing some minor typos

---

cmd/common.go
cmd/diff.go
cmd/sync.go
diff/diff.go

decK first creates all the services and then creates related routes.
With a distributed like Cassandra, route creation happens before
the DB rows for new services are propagated to other nodes in the
cassandra cluster. This results in a 409 from kong because kong ensures
that service specified in a route is actually present in the db (c* has
no notion of foreign relations, kong does a read on the service to
verify and enforce foreign key relations).
With the new configurable flag, users of cassandra can inject an
aritifical between insert operations of related entities to avoid failures
described above. The use of the flag is discouraged and is only
implemented to provide a stop-gap solution.
Fix #160
Fix #154

feat(sync) configurable artificial delay for cassandra deployments

---

dump/dump.go

When getting entities from Kong, decK will restrict the query to the tags in the state files. However, when using multiple state files, it will AND all tags it finds together - regardless of whether they are unique tags or just the same tags.
When the total number of tags is above 5, Kong will reject the query outright.
This PR deduplicates tags before they are sent to Kong. This allows having the same tag(s) in every file (to make sure it is never synced tag-less) - as long as the total unique number is not above 5.

fix: Deduplicate tags before sending to Kong

---

cmd/common.go
cmd/diff.go
cmd/sync.go

Allow specifying a workspace with `-w / --workspace` for the `sync` and `diff` commands - similar to how this is possible today for `dump` and `reset`.
1. Enables rolling out the same configuration across workspaces, e.g. the same logging plugin.
2. Easier sharing of deck configurations between Kong deployments (e.g. between different organizations, or different parts of the same organization), where the eventual workspace names cannot be known beforehand.

feat(sync/diff) Add workspace arg to sync and diff commands

---

file/writer.go

mtls-auth credentials can be tied to CACertificate.
This leads to a probelm where mtls-auth credential can contain an ID of
a CACertificate but CACertificate is exported to state file without an
ID. Now, on a subsequent `sync` from scratch, the ID of CACertificate
will be auto generated. This breaks the link between mtls-auth
credential and CACertificate, and the sync fails.
With this patch, like Certificate entity, ID of CACertificate is always
exported, no matter what.

feat: always export ID for CACertificate

---

cmd/common.go

When decK encounters an error (e.g. invalid plugin configuration) it will currently not print the summary, making it hard to know what was still changed despite the error.
This small change makes sure the summary is printed even in that case and adds an `Errors:` field when there was at least one error.
Sample output:
```ShellSession
$ ./deck sync -s .
creating consumer jwt-user
...
...
...
creating plugin openid-connect for route 8e4bf008-c470-4456-b333-7094c7089070
Summary:
Created: 112
Updated: 15
Deleted: 0
Errors: 2
Error: 2 errors occurred:
while processing event: {Create} failed: 400 Bad Request {"message":"2 schema violations (only one of these fields must be non-empty: 'config.aws_region', 'config.host'; config.aws_region1: unknown field)","name":"schema …
```

feat(sync): Always print summary

---

crud/registry.go
solver/solver.go

When dealing with many errors, it can be hard to map the error messages (which all appear together at the very end of the output) to the entities (which appear all before). This PR adds information about the kind of entity and the entity identifier to the error messages.
*Before (showing just one error for brevity, and coincidentally the identifier is also in the error message - however, this really matters esp. when there are dozens of errors and the errors have less detail):*
```ShellSession
$ deck sync -s .
creating consumer acl21
Summary:
Created: 0
Updated: 0
Deleted: 0
Error: 1 errors occurred:
while processing event: {Create} failed: 409 Conflict {"message":"UNIQUE violation detected on '{username=\"acl21\"}'","name":"unique constraint …
```

feat: Print entity identifier in errors

---

cmd/common.go

#157 and #158 being merged simultaneously created a bug where decK would not take into account the workspace specified with `--workspace` when creating a new workspace. This is the fix.

fix: Create specified workspace

---

file/reader.go
state/aclgroup.go
state/cacert.go
state/certificate.go
state/consumer.go
state/credentials.go
state/plugin.go
state/route.go
state/service.go
state/sni.go
state/target.go
state/upstream.go
state/utils.go

Currently, when an entity is duplicated in the state file(s) the error message is not very helpful, e.g.:
```ShellSession
$ deck validate
Error: entity already exists
```
In a large and distributed configuration, it is often not easy to figure out which entity this is. Also, the error message itself does not say *where* the entity already exists - it could mean *exists in Kong*.
With this PR, the error message becomes a lot more helpful:
```ShellSession
$ ./deck validate
Error: error reading state file(s): consumer consumer1 already exists
```
This applies across `deck sync`, `deck diff`, and `deck validate`.

feat: Print detailed entity information when it already exists

---

docs/development/release.md

Update release instructions with changes we found during the 1.2.2 release and additional examples.
As far as I know, nothing changed in the Docker release process, and the existing text already matches what we had in the temporary Google doc. @mflendrich as you took over following my computer issues, please let me know if that's not the case and I missed something that we need to update.

docs(release) update release instructions

---

cmd/common.go
cmd/dump.go
cmd/ping.go
cmd/reset.go
cmd/root.go
utils/types.go

fixes #218 
replaces #219 
This PR:
- cleans up deck's usage of non-workspaced ("root") and workspaced clients and configs,
- makes workspaceExists() GET `/<workspaceName>/routes/` instead of `/workspaces/<workspaceName>` because users of deck are much more likely to have permissions to access the latter endpoint, rather than the former (e.g. in a case where the calling user is a workspace admin and has permissions only within the namespace)
The change seems justified because it appears impractical to use deck on a workspace without read permissions to the `/<workspaceName>/routes/` endpoint.

feat: reimplement workspaceExists() without the /workspaces endpoint

---

file/readfile.go
file/readfile_test.go

`go-yaml` marshals into `map[interface{}]interface{}`.
This change ensures that `map[interface{}]interface{}` is converted into
`map[string]interface{}` RECURSIVELY.
~This patch needs tests before it can be merged.~ Added a test.
See #144

fix(file) convert yaml to JSON

---

CHANGELOG.md

Changelog updates to tentatively release this on Wednesday. Commits to a date in advance, but I'd expect that there isn't much that'd need to change, and the remainder of https://github.com/Kong/deck/blob/main/docs/development/release.md can be done independently after the changelog updates are merged.

Document changes for v1.2.3

---

state/types.go
state/types_test.go

Ignore tag order for object comparisons by sorting the string slices that contain them before checking object equality. This avoids issues with spurious diffs resulting in unnecessary changes when the tag order constructed by deck from dump YAML and the tag order reported by admin API JSON differ.
Because Kong object tags are logical string sets, their order does not matter: it is only a perceived difference because JSON and YAML lack set types and represent them with ordered arrays.
Fix #239 and a minor typo ("Copt" to "Copy" in one of the functions).
**Implementation notes/questions:**
We have `Equal()` and `EqualWithOpts()` functions for each object. The former is just `return reflect.DeepEqual(thing1, thing2)`, is not modified by this PR, and would still report the objects not equal …

fix(types) ignore tag order for object comparisons

---

cmd/root.go

We originally set the verbosity config after loading it from the `--verbose flag`. #225's changes to fix workspace issues [grouped that config set with other config settings, before loading the `--verbose` flag value](https://github.com/Kong/deck/compare/v1.2.2...v1.2.3#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fL157-L166). As a result, deck always uses the default verbosity.
This change moves the `--verbose` flag load above those settings, restoring the ability to control verbosity.
Originally reported internally in FTI-2144. FWIW, no-color is still after everything in that block, but that doesn’t appear to matter/it’s still applied correctly in 1.2.3. Didn’t dig into how that works, but it doesn’t appear that needs a similar fix, so left it alone.

Fix --verbose

---

README.md

Per planning, we want to codify our stale issue/PR policy for our team's major community-facing repos. This updates our contributing documentation to reflect that. There's no separate contributing document for deck, so added

Add stale issue policy

---

cmd/analytics.go
cmd/root.go

With this patch, analytics is sent only on a best-effort basis.
Failure to send analytics doesn't result in any slowdown for the end
user.
Fix #253

fix: send analytics on a best effort basis

---

cmd/common.go

https://github.com/Kong/deck/pull/225/files#diff-2b0546a527b3560f4e7f8501ef7907999b2e1a7f2498a60719630310f7778956R74 attempts to create a workspace with no name, as we only populate it in https://github.com/Kong/deck/pull/225/files#diff-2b0546a527b3560f4e7f8501ef7907999b2e1a7f2498a60719630310f7778956R84-R86
Fix appears to be using `wsConfig` instead; that works when testing manually.
@mflendrich it looks like this was probably unintentional leftovers from an earlier draft before the commit was pushed. Do you recall if there's any reason we would indeed want to use `rootConfig` here? Doesn't look like it based on a brief review of the [wsConfig population code](https://github.com/Kong/deck/blob/main/utils/types.go#L82-L87) and [go-kong workspace …

Fix regression preventing workspace creation

---

file/readfile.go

fixes #255 
Before this PR, `configFilesInDir()` treats paths `emptyfiles/not-a-file.yaml/info.txt`, `emptyfiles/foo.notyaml` and `emptyfiles/foo.yaml.pdf` as YAML/JSON files.
After this PR, `configFilesInDir()` no longer returns the above paths as yaml/json files.
The updated test did not pass before the code change and passed after the code change (TDD).
This PR replaces the regexp match in `Walk` by `strings.ToLower(filepath.Ext(path))`.

fix(file): configFilesInDir extension match (#255)

---

.goreleaser.yml

See https://goreleaser.com/deprecations/#brewsgithub

Update goreleaser brew syntax

---

CHANGELOG.md

This adds changelog notes to release `v1.4.0`

docs(changelog): document changes for v1.4.0

---

state/target.go
state/target_test.go

target.Target represents an IP address or a DNS name in Kong. These can
be same across different Upstreams.
Drop the unique index on Target resource for this reason.
This is similar to the fix applies to ServiceVersion resource in
cf44212.
The test has been updated to remove insertion of Upstream which doesn't
add in value.
Fix #233

fix(state) drop index on target.Target

---

file/writer.go
solver/utils.go
utils/zero.go

fix: do not print timestamps in diff output

---

.goreleaser.yml

chore: use go's -trimpath instead of asmflag

---

cmd/konnect_diff.go
cmd/konnect_dump.go
cmd/konnect_sync.go

Use separate variables to store Konnect command flag values where Konnect commands share flags with non-Konnect commands.
Cobra will otherwise update the variable contents with whichever flags it processes last, effectively overriding the non-Konnect defaults with the Konnect defaults.
I don't think anything wants a different default value currently other than the state file, but I think we should define new variables for everything that's not actually being inherited from a parent command for consistency and safety in the event of future changes to one command set's defaults.
Fix #288

fix(cmd) use separate variables for Konnect flags

---

.goreleaser.yml

Homebrew 3.0.8 enforces a new restriction on formula commands. They must
be separated into their components to avoid errors like the following:
```
Separate `system` commands into `"#{bin}/deck", "version"`
```
See https://travis-ci.com/github/Kong/homebrew-deck/builds/220979410 for an example failed build.
https://github.com/Homebrew/brew/pull/10873 is the related upstream change.

fix(build) update brew formula for 3.0.8

---

cmd/root.go
main.go

This incorrect change was introduced in 4717d53.

hotfix: fix double error message prints

---

dump/dump.go

Treat a 403 on the mtls-auth endpoint the same as a 404. This handles the endpoint's behavior in Enterprise free mode gracefully, whereas previously the dump would fail entirely.
We eventually want a way to properly determine if an instance is in Enterprise free mode and avoid unavailable API calls entirely rather than relying on the return code.
Fix #274

fix(dump) add workaround for free mode mtls-auths

---

file/readfile.go
file/readfile_test.go
file/testdata/bad-env-var/file.yaml
file/testdata/file.yaml

Introducing support for envirment variable substitution in state files.
This is primarily intended for injecting sensitive data at runtime.
Fix #191

feat(file) implement env var substitution for state files

---

dump/dump.go

I goofed checking 8254879 and only confirmed the negative case :facepalm: 
We don't want this to happen if the mTLS auth credentials endpoint _is_ available:
```
$ /tmp/main-deck dump -o main.yaml
panic: interface conversion: error is nil, not *kong.APIError
goroutine 36 [running]:
github.com/kong/deck/dump.GetAllMTLSAuths(0xc80cb8, 0xc000139240, 0xc000172400, 0xf592b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/traines/src/deck/dump/dump.go:671 +0x5b5
github.com/kong/deck/dump.getConsumerConfiguration.func8(0x0, 0x0)
/home/traines/src/deck/dump/dump.go:128 +0xef
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0001dd2c0, 0xc000142f50)
/home/traines/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x85
created by golang.org/x/sync/errgroup.(*Group).Go …
```

fix(dump) address free mode workaround regression

---

file/types.go

Disable deepcopy-gen on the file.foo and file.service types.
Requesting deepcopy-gen on these types _sometimes_ led to CI failures, e.g. https://github.com/Kong/deck/pull/343/checks?check_run_id=2421543562
Typically, deepcopy-gen simply ignores these types. Although unexported types [are not supported](https://github.com/kubernetes/gengo/blob/de9496dff47bef4ff8f45a56096bf50798cba2a5/examples/deepcopy-gen/generators/deepcopy.go#L405-L407), it just [logs that it cannot generate code for them and skips over them](https://github.com/kubernetes/gengo/blob/de9496dff47bef4ff8f45a56096bf50798cba2a5/examples/deepcopy-gen/generators/deepcopy.go#L270-L273). However, there is an initial check to see if anything in a package needs code generation, and this check [throws a fatal error if it encounters …

fix(file) disable deepcopy-gen for invalid types

---

konnect/types.go

Konnect API's behavior seems to be that if one sends a PATCH request without
an explicit `null`, that property is not reset to empty.
After removal of `omitempty`, deleting `description` field from the
state file correctly updates the description in Konnect.

fix: set description to null to reset description

---

utils/types.go
utils/types_test.go

Why?
go-kong ships with header injection utility which can be used directly.
This was not possible when decK was first written.
This reduces some code duplication.

refactor: use go-kong's header injection

---

cmd/common.go
cmd/common_konnect.go
cmd/diff.go
cmd/dump.go
cmd/ping.go
cmd/reset.go
cmd/root.go
cmd/sync.go
diff/diff.go
dump/dump.go
dump/dump_konnect.go
main.go
reset/reset.go
solver/solver.go

This patch is an effort to improve the context propagation in decK, down
to every single operation.
In order to do that, a single root context is now being created in the
main function, and all contexts should be derived from it.

refactor: plumb a single context throughout the code

---

cmd/common.go
cmd/dump.go
cmd/konnect_diff.go
cmd/konnect_dump.go
cmd/konnect_ping.go
cmd/konnect_sync.go
cmd/ping.go
cmd/reset.go
cmd/root.go
cmd/validate.go
go.mod
go.sum
utils/analytics.go

Analytics were temporarily removed as we sent them to a third-party
server.
With this new implementation, these are being sent to Kong Inc directly.
Furthermore, to alleviate concerns raised
in https://github.com/Kong/deck/pull/242, we are now providing a flag on
the root-level, in addition to DECK_ANALYTICS environment variable to
tweak the setting.

feat: introduce usage analytics

---

diff/cert.go

The first commit here is a noisy chore. Review 6de9ee254abadc2c4b9fa0987f49844208b4239c for the meat of this change.
#356 occurs when updating a certificate without modifying its SNIs. We strip SNIs from certificate objects to handle SNIs separately, but the Kong admin API behavior for certificate PUTs handles an empty SNI set on certificates as an instruction to _delete_ those SNIs (probably because SNIs can't exist independent of certificates and because there's a strict one-to-one certificate-to-SNI relationship).
To work around this, this change copies the existing certificate's SNIs out of state during updates and sets them on the updated certificate object before sending it. This preserves the SNI list if it is unchanged while still updating SNIs if they do change (subsequent diffs …

Do not destroy SNIs when updating unrelated certificate fields

---

cmd/common.go
cmd/reset.go

- reset command follows the same code path as diff and sync commands
i.e. entities are exported and reset using the syncer itself, this gets
rid off reset package entirely and minimizes the amount of code that
needs to be maintained
- Previously, we relied on kong's "on-cascade-delete" meaning, only a
single DELETE request was sent to delete a service, which in turn
deleted all the routes of the service and all the plugins on those
routes, services,etc. Now, reset will delete each and every entity in
the correct order (same as diff and sync). This results in a decrease in
performance of reset command as it will take longer. I don't expect this
to be a problem since reset command is used less often and with
concurrent nature of decK, this should not be a burden.

refactor: drop reset package to simplify codebase

---

file/kong_json_schema.json
scripts/verify-codegen.sh

The refactor introduced in #413 caused a bug in the verify script which
resulted in an outdated schema after #419.
This fixes the schema and the verify script.

fix: update codegen and fix verify script

---

diff/diff.go

Document object in Konnect are always associated with either a service
package or a service version.
- If a service version or package is deleted, deleting a document
results in a 404, an error in decK
- If a document is created before the corresponding service package or
version is created, it resulted in 400, again an error
This patch adds the appropriate barriers to prevent such races.

fix: document creation and deletion race with parent objects

---

types/core.go

This reverts a mistake that was introduced in #436.

hotfix: correct the kind for HMACAuth

---

cmd/root.go
utils/types.go

Set client timeout https://github.com/Kong/deck/issues/449

---

dump/dump.go
file/builder.go
file/reader.go

Please see #414 for some background and an alternate solution that was
considered but had to be dropped for backwards-compatibility reasons.
This patch fixes the following bugs:
- file package
- statebuilder sets tags on credentials conditionally but the variable
containing the version of kong was never being set in the first place.
We do that correctly now. Please note that we don't set these
variables for the code-path for Konnect because control-plane in
Konnect is not-versioned from our customer's perspective. That and
select-tag feature is not available in Konnect.
- mTLS auth credentials received tagging support in Kong Enterprise
2.3. decK will now set the select-tag in mtls-auth credentials when
Kong version is compatible.
- dump package:
- #282 incorrectly only exported tagged …

fix: multiple bugs with credentials and select-tags

---

cmd/convert.go

Previously, KongGateway was listed in --to and Konnect was listed in
--to, which wasn't supported.
This fixes the documentation so that the user isn't confused anymore.

fix: correct formats where conversion is allowed

---

.github/workflows/codeql-analysis.yml

In https://github.com/Kong/deck/runs/3510966256?check_suite_focus=true we can see
>Extraction failed in file/schema.go with error package embed is not in GOROOT (/opt/hostedtoolcache/go/1.15.15/x64/src/embed)
But embed is a 1.16 capacity, using 1.16 is fixing it

chore(ci): codeql-analysis on go 1.16

---

.github/workflows/release.yaml

Adds tag push CI jobs that run goreleaser, upload dist output, and build/push images to Docker Hub.
This will absolve us of the need to generate temporary kongbot tokens to push to the Kong Docker Hub. goreleaser has a good simple action also, so may as well add that too to automate the rest of the release.
The goreleaser job uploads dist output to the action artifacts for handling Homebrew releases.
This **does not work yet**. It requires HARRY_DOCKER_USERNAME, HARRY_DOCKER_TOKEN, DOCKER_USERNAME, and DOCKER_TOKEN secrets to actually push to Docker Hub. These should have access to Harry's registry and the Kong registry, respectively.
Example results: https://github.com/rainest/deck/runs/3943012130
```
11:21:46-0700 yagody $ docker run traines/altdeck:v1.8.11 version
decK …
```

Automatically release on tag push

---

cmd/common.go
cmd/common_test.go
cmd/validate.go
file/builder.go
file/builder_test.go
file/reader.go

When syncing entities, use the tags from either --select-tag or state file metadata. Previously, sync only used file metadata for assigning tags to new resources, and --select-tag would only filter entities from the current state for comparison.
If the tags requested by --select-tag and file metadata differ, fail the sync.
Fix #362
This maybe needs some historical information about the development of `--select-tag` to say whether it's actually by design--this does address the issue raised by #362, but is a fairly significant change, so I wanted some confirmation that it does indeed appear to be an unintended omission rather than intentional for some reason.
Without this change, `--select-tag` only filters entities from the current state. Proposed entities will be compare to these, but …

fix(sync) apply --select-tag to new entities

---

diff/diff.go

If a sync context ends, return its Context.Err() in the list of sync errors. This informs downstream clients that the sync did not process all entities, even if there were no events in flight (which generate their own errors, as seen below) at the time the context ended. On the user end, this will look like:
```
11:52:27-0800 esenin $ /tmp/bdeck sync -s /tmp/foo.yaml
creating consumer foo
...
creating upstream foo.8080.svc
^Creceived interrupt , terminating...
Summary:
Created: 17
Updated: 0
Deleted: 0
Error: 5 errors occurred:
sync context ended, some entities were not synced: context canceled
while processing event: {Create} upstream bar.8001.svc failed: making HTTP request: Put "http://localhost:8001/upstreams/3acc5ce0-6a3b-40d2-a63c-6ab73d1db221": context canceled
...
```
Fixes #528

fix: return error when sync context ends

---

diff/diff.go
diff/order.go
diff/order_test.go

Kong and Konnect's data-model is relational in nature. This requires
decK to order its operations in a certain fashion. Creating an entity
without first ensuring that the present is present results in
violations. Deleting on the other hand, requires deleting every single
child before a parent is deleted to properly account for edges of the
entity relationship graph.
This was historically done by ordering entities in a particular order.
This was prone to some error, but even more so, very hard to grok for
anyone maintaining or reading the code.
This change builds upon the previous refactors(#435,#436) and decouples
the ordering of entities.
The dependency graph has been built up from ground up again to account
for all of 21 entities that decK can manage today.
Most of these entities were …

refactor: simplify dependency definitions

---

cmd/common.go
cmd/sync.go

In order to have `--skip-consumers` work as expected with the `sync` command, 2 things need to happen:
- `consumers` to be ignored on fetched current state
- `consumers` to be ignored on generated target state
The first bullet is currently taken care of [here](https://github.com/Kong/deck/blob/main/dump/dump.go#L259-L260), which is called by the `syncMain` function [here](https://github.com/Kong/deck/blob/main/cmd/common.go#L189).
The second bullet is what we are currently missing.
**Before the change in this PR:**
```
services:
- name: svc1
host: mockbin.org
retries: 5
tags:
- team-svc1
consumers:
- username: yolo
$ http :8001/consumers
{
"data": [],
"next": null
}
$ ./deck sync --skip-consumers
creating consumer yolo
Summary:
Created: 1
Updated: 0
Deleted: 0
```
Not only …

fix: skip consumers when using --skip-consumers with the sync command

---

dump/dump.go
dump/dump_konnect.go
dump/dump_konnect_test.go
konnect/utils.go

Plugins created by Konnect for internal-use only
are tagged with 'konnect-managed-plugin'. decK should not allow users to
interact with any plugins with this tag.
This skips plugins with internal-only konnect tags.

feat: don't manage Konnect internal-only plugins

---

cmd/common.go
cmd/validate.go
main.go
utils/utils.go
validate/validate.go

Hi! In order to get more familiarity with the tool and the codebase, I decided to give it a try and work on the proposal discussed in https://github.com/Kong/deck/issues/190
Sample usage:
```
$ deck validate --help
The validate command reads the state file and ensures validity.
It reads all the specified state files and reports YAML/JSON
parsing issues. It also checks for foreign relationships
and alerts if there are broken relationships, or missing links present.
When ran with the --use-kong-api flag, it also uses the 'validate' endpoint in Kong
to validate entities configuration.
Usage:
deck validate [flags]
Flags:
-h, --help                  help for validate
--rbac-resources-only   indicate that the state file(s) contains RBAC resources only (Kong Enterprise only).
-s, --state strings …
```

feat: add support to validate via Kong API

---

cmd/root.go

Currently decK collects and shares anonymized data with Kong.
This feature is controlled via the '--analytics' flag,
which is True by default. The flag description doesn't
describe how users can prevent decK to share this data though.
This PR makes it clear to use --analytics=false for that.
Related to https://github.com/Kong/deck/issues/399

style: clarify how to disable 'analytics'

---

cmd/konnect_ping.go

Related to https://github.com/Kong/deck/issues/568

fix: konnect ping ignores analytics flag

---

cmd/common.go
cmd/common_test.go
utils/utils.go

When running sync with multiple files and `--select-tag`,
deck simply appends the existing `_info.select_tags` of the
various files. If the same tag(s) are present in the files,
these are appended together making `deck` fail because the
tags passed via the command flag and the ones coming from
the files are expected to match, but the way files are
merged may cause duplicates, hence the unexpected failure.
This removes duplicates from the _info.select_tags resulted
from the merged files.
Related to https://github.com/Kong/deck/issues/561

fix: unexpected error with --select-tag and multiple files

---

go.mod
go.sum

This makes us able to set zero-value fields and not have them overwritten from non-zero value defaults.
Before:
```
upstreams:
- name: upstream1
algorithm: round-robin
targets:
- target: 198.51.100.11:80
weight: 0  # default being 100
$ deck sync
<--omitted-->
$ http :8001/upstreams/upstream1/targets | jq ".data[0].weight"
100
```
After:
```
$ deck sync
<--omitted-->
$ http :8001/upstreams/upstream1/targets | jq ".data[0].weight"
0
```

chore(deps): update mergo

---

file/readfile.go
file/readfile_test.go
file/testdata/differentworkspace/bar.yaml
file/testdata/differentworkspace/foo.yaml
file/testdata/sameworkspace/bar.yaml
file/testdata/sameworkspace/foo.yaml
file/validate.go

When passing to `sync` multiple files (or a folder) with different
_workspace definition, sync merges the files and applies them
only to a single workspace.
This change makes `sync` returning an error when attempting
a deployment with multiple workspaces.

fix: unexpected behaviour with sync and multiple ws

---

.goreleaser.yml

I tested this as follows:
- on my [forked repo](https://github.com/GGabriele/deck), I created and pushed a new tag to simulate a release
- I ran `goreleaser release --snapshot --rm-dist` locally to generate the artifacts and include them in a [new release](https://github.com/GGabriele/deck/releases/tag/v1.10.0-testing)
- modified the generated `dist/deck.rb` file to point brew at my repo instead of `Kong/deck`
- use the local file with brew (note this is pulling the `*_darwin_all.tar.gz` "universal" artifact)
```
$ brew install dist/deck.rb
Error: Failed to load cask: dist/deck.rb
Cask 'deck' is unreadable: wrong constant name #<Class:0x000000015b96e108>
Warning: Treating dist/deck.rb as a formula.
==> Downloading https://github.com/GGabriele/deck/releases/download/v1.10.0-testing/deck_v1. …
```

chore: release Fat/Universal binaries for macOS

---

validate/validate.go
validate/validate_test.go

```
$ deck validate --online
Error: validate entity 'services (svc1)': HTTP status 400 (message: "schema violation (host: must not have a port)")
validate entity 'certificates (13c562a1-191c-4464-9b18-e5222b46035b)': HTTP status 400 (message: "2 schema violations (cert: invalid certificate: x509.new: asn1/tasn_dec.c:309:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error; key: invalid key: pkey.new:load_key: nil failed)")
validate entity 'plugins (prometheus)': HTTP status 400 (message: "schema violation (protocols.1: expected one of: grpc, grpcs, http, https, tcp, tls, tls_passthrough, udp)")
validate entity 'snis (demo1.example.com:123)': HTTP status 400 (message: "schema violation (name: must not have a port)")
```

feat: improve validate output

---

file/builder.go
tests/integration/sync_test.go
tests/integration/testdata/sync/006-fill-defaults-rate-limiting/kong.yaml
tests/integration/testdata/sync/007-fill-defaults-rate-limiting-dedup/kong.yaml

Defaults ingestion is happening before filling the
de-duplicate plugins configuration, meaning that
de-duplicate plugins will not benefit of automatic
defaults.
This reverts the order of the two operations.
Before:
```
_format_version: "2.1"
_plugin_configs:
rate-limiting-one:
minute: 6000
policy: local
hide_client_headers: true
services:
- name: sample
url: https://example.org
plugins:
- name: rate-limiting
_config: rate-limiting-one
routes:
- name: sample
paths:
- /sample
```
```
$ deck sync
creating plugin rate-limiting for service 6c11f78b-4b12-4556-8058-0bb26832c076
Summary:
Created: 0
Updated: 0
Deleted: 0
Error: 1 errors occurred:
while processing event: {Create} plugin rate-limiting for service 6c11f78b-4b12-4556-8058-0bb26832c076 failed: HTTP status 400 (message: …
```

fix: plugin defaults ingestion breaks dedup

---

cmd/completion.go
cmd/convert.go
cmd/diff.go
cmd/dump.go
cmd/konnect.go
cmd/konnect_diff.go
cmd/konnect_dump.go
cmd/konnect_ping.go
cmd/konnect_sync.go
cmd/ping.go
cmd/reset.go
cmd/root.go
cmd/sync.go
cmd/validate.go
cmd/version.go
docs/generate-docs.go
tests/integration/sync_test.go

The current version of the `cmd` package is structured
around some global variables holding the `cobra` commands.
This makes the package hard to test.
This reworks the `cobra` commands definition with 'constructor' helpers.
This also rearranges the existing flags, moving the ones specific
to `konnect` under the `konnect` subcommand.

feat: refactor cmd package

---

file/builder_test.go

Edit: the original rationale was wrong, I didn't realize we needed to re-add the mergo replace to KIC modules. This is now only the test.
https://github.com/Kong/kubernetes-ingress-controller/pull/2286 failed when trying to add v1.11.0 to KIC. Something appears to have happened after I tested with https://github.com/Kong/deck/pull/573.
Within ingresRoute, the value is `false` as expected after it's set to the result of `getStripPathBasedOnProtocols()`. It flips back to `true` after https://github.com/Kong/deck/blob/v1.11.0/file/builder.go#L786
I thought this maybe meant something didn't work as expected with https://github.com/Kong/deck/pull/580, but as these were already `*bool` any non-nil value is not zero, so I'm not sure why the default was merging over the original value.
The change …

fix(builder) set strip_path after defaults

---

cmd/common.go
file/builder.go
file/reader.go

Refactor the target config side of the --skip-ca-certificates implementation to use the dumpConfig setting inside file.Get() rather than stripping CA Certificates from target configuration afterwards.
As-is we'd need to duplicate the logic to strip certificates out of target config downstream (see https://github.com/Kong/kubernetes-ingress-controller/pull/2341/commits/3b926bd7493cc4636d984c7a4274e403fb465909#diff-d8590e8687e7807da0cf97910b88e0ddbfc670866e0973a15c56597b99df9244R209-R214) which we don't want--it's simple, but it could potentially diverge. This allows us to use a single implementation internal to deck.

chore(file) refactor target config cert omission

---

cmd/common.go

We already use to remove duplicates from `select_tags`, but only when tags are also passed via CLI flags. 
Solves https://github.com/Kong/deck/issues/614

fix: remove duplicates in select_tags

---

docs/development/code_structure.md

This is a copy of the onboarding overview document I presented earlier this year. I originally stuffed it in Confluence, but it's probably more discoverable (and accessible to non-Kong contributors) here.

doc: add code overview

---

file/builder.go
tests/integration/diff_test.go
tests/integration/test_utils.go
tests/integration/testdata/diff/001-not-existing-workspace/kong.yaml
utils/defaulter.go
utils/types.go
utils/utils.go

The new defaulter interacts with Kong API to retrieve
entities schemas. Doing such query against a not existing
workspace returns an error, blocking the diff operation in decK.
This makes sure decK can run 'diff' regardless of the workspace
by simply not retrieving entities schemas from Kong when the
workspace doesn't exist yet.
Solves https://github.com/Kong/deck/issues/601#issuecomment-1057647420

fix: support defaulter with not-existing workspaces

---

file/builder_test.go
utils/constants.go
utils/defaulter.go
utils/defaulter_test.go

I spend some time yesterday to implement a validation for #421. It could have been simpler by just checking the object fields directly with if statements, but I was interested to learn a bit about the **reflect** module.
To check; this implementation do the validation *after* the user input injection, which mean that the defaults in `constants.go` can still be applied without validation. 
```shell
$ ./deck validate
Error: building state: creating defaulter: 3 errors occurred:
service defaults cannot have these restricted fields set: id, name
route defaults cannot have these restricted fields set: id, name
upstream defaults cannot have these restricted fields set: id
...
```
TODO:

Add basic validation for restricted fields

---

docs/generate-docs.go

In the docs repo, changes are often made to autogenerated files instead of the source files, and they aren't always caught. We've just added a check on docs PRs in docs.konqhq.com to catch those instances: https://github.com/Kong/docs.konghq.com/pull/3841
Any generated files now must contain a `source_url` entry in their frontmatter. When a pull request changes a file that contains this entry, a warning will be added as a comment. You can see that in effect here: https://github.com/Kong/docs.konghq.com/pull/3861
Adding the source_url param to all decK CLI generated docs.
Tested by running `make generate-cli-docs` from my branch, output looks right:
```
---
title: deck sync
source_url: https://github.com/Kong/deck/tree/main/cmd
---
The sync command reads the state file and performs …
```

Apply source_url param to generated docs

---

cmd/convert.go

```
$ ./deck convert --from kong-gateway --to konnect --input-file kong.yaml --output-file kong.konnect.yaml
Notice: The `konnect` format type has been deprecatedas of v1.12.
Please use the `kong-gateway` format with `deck <cmd>` if you would like
to declaratively manage your Kong gateway config in Konnect.
```

feat: add deprecation notice to 'convert' for konnect

---

CHANGELOG.md

Adds an unreleased 1.13 changelog. Per https://github.com/Kong/deck/pull/662#discussion_r862110930 we should start adding these as we make PRs to reduce release tasks and ensure we don't miss important changes when reviewing older PRs prior to release.
The changelog items include user-facing changes since 1.12 based on my review of closed PRs as of today.

doc: add unreleased 1.13 changelog

---

CHANGELOG.md
file/reader_test.go
file/testdata/config.yaml
file/types.go

Without this decK is failing at parsing the 'enabled' field
for services entities.

fix: populate missing 'enabled' service field from file

---

CHANGELOG.md
file/builder.go
file/builder_test.go
state/builder.go
state/rbac_endpoint_permission.go
state/rbac_endpoint_permission_test.go
state/types.go
tests/integration/sync_test.go
tests/integration/test_utils.go
tests/integration/testdata/sync/002-create-services-and-routes/kong.yaml
tests/integration/testdata/sync/003-create-a-plugin/kong.yaml
tests/integration/testdata/sync/008-create-simple-entities/kong.yaml
tests/integration/testdata/sync/010-create-route-with-service-name-reference/kong.yaml
tests/integration/testdata/sync/xxx-plugins-on-entities/kong.yaml
types/ca_cert.go
types/certificate.go
types/consumer.go
types/postProcess.go
types/rbac_endpoint_permission.go
types/rbac_role.go
types/route.go
types/service.go
utils/utils.go

Based on the initial work in https://github.com/Kong/deck/pull/459
Changes from the first PR:
- rebased on top of `main` and solved conflicts
- reworked a bit some logic
- added nil checks
- reworked and reorganized commits and commits messages for an (hopefully) easier review process

feat: logs friendly names with plugins

---

types/plugin.go
types/route.go

Kong and Konnect APIs only require IDs for referenced entities.
In some cases, injecting the entities name in the requests is
problematic. This makes sure these names are stripped before making
API requests, while preserving the capability of logging user-friendly
messages as added in https://github.com/Kong/deck/pull/662

fix: strip references name for plugins and routes

---

CODEOWNERS

This patch updates the CODEOWNERS file to the new team that owns deck.

docs: update CODEOWNERS

---

diff/order.go

Right now, `Upstream` entities are computed concurrently with
`Certificates`. This may lead to ordering errors because an `Upstream`
can reference `Certificates` objects in the 'client_certificate' field.
This PR makes sure Upstreams changes are pushed after Certificates.

fix: upstreams changes should be pushed after certs ones

---

CHANGELOG.md
cmd/common_konnect.go

Before:
```
$ deck dump --yes --select-tag team-svc1
$ cat kong.yaml # missing select_tags
_format_version: "1.1"
_info:
defaults: {}
_konnect:
runtime_group_name: default
services:
- connect_timeout: 60000
enabled: true
host: mockbin.org
name: svc1
port: 80
protocol: http
read_timeout: 60000
retries: 5
tags:
- team-svc1
write_timeout: 60000
```
After:
```
$ deck dump --yes --select-tag team-svc1
$ cat kong.yaml # included select_tags
_format_version: "1.1"
_info:
defaults: {}
select_tags:
- team-svc1
_konnect:
runtime_group_name: default
services:
- connect_timeout: 60000
enabled: true
host: mockbin.org
name: svc1
port: 80
protocol: http
read_timeout: 60000
retries: 5
tags:
- team-svc1
write_timeout: 60000
```

fix: correctly set select_tags when dumping from Konnect

---

file/builder.go
tests/integration/testdata/diff/001-not-existing-workspace/kong.yaml

decK dynamically discovers entities defaults by interacting
with the Kong Admin API. Queries to retrieve entities schema
for a workspace that doesn't exist yet would fail though.
When running `diff`, in order to prevent a failure, decK simply
skips defaults injection for all entities, but it was still
wrongly running queries for plugins, making the run fail.
This PR makes sure plugins defaults injection is treated the
same as other entities when running `diff` against a
not-existing workspace.
Solves https://github.com/Kong/deck/issues/697

fix: diff with not-existing WS must not fail due to defaults

---

.github/workflows/integration-enterprise.yaml
file/kong_json_schema.json
file/types.go
go.mod
go.sum
tests/integration/sync_test.go
tests/integration/testdata/sync/011-plugin-ordering/kong.yaml

Add support for the new plugin ordering field. Draft pending https://github.com/Kong/go-kong/pull/187 and a go-kong release.

Add support for plugin ordering

---

diff/diff_helpers.go
go.mod
go.sum

Update gojsondiff to incorporate the fix from https://github.com/Kong/gojsondiff/pull/3 and replace upstream gojsondiff with our fork in diff_helpers.go.
Fix https://github.com/Kong/deck/issues/722
The combination of removing references to upstream go-diff in gojsondiff fork 1.3.2 and replacing references to upstream gojsondiff here removes the leftover requires for upstream go-diff mentioned in #726.

 chore(deps) update gojsondiff to v1.3.2

---

file/builder_test.go
file/kong_json_schema.json
go.mod
go.sum
tests/integration/sync_test.go

Adds new upstream fields for 3.x.
Fix #734.
Requires a new go-kong release that includes https://github.com/Kong/go-kong/pull/200. Currently using a main hash.

Add 3.x upstream fields

---

cmd/common.go
cmd/root.go

Right now decK runs against Konnect if some Konnect
credentials are around, either via command flags or via
environment variables. In the case of having a `kong-addr`
different from the default value and some lingering Konnect
credentials environment variables set, decK would still
decide to run against Konnect instead of Kong.
This PR is reworking the order of precedence gating Konnect:
1. if the config file contains the `_konnect` entry, run
against Konnect
2. if the `kong-addr` is set to a non-default value, run
against Kong
3. if some Konnect credentials are set, run against Konnect
4. otherwise run against Kong

fix: correct order of precedence to gate Konnect mode

---

CHANGELOG.md
cmd/common_konnect.go

Recently we made `decK` more aware of the `_format_version` value, which require fetching the Kong version from Admin API. This is not possible for Konnect right now, so we just hardcoded it for `sync`, but missed it for the `dump` command.
This commit is fixing it.

fix: dump with Konnect is missing Kong version

---

CHANGELOG.md
cmd/sync.go

Right now `dump` supports both `--workspace` and `-w`, while `sync` only supports `--workspace`.

fix: add -w shorthand flag support to sync

---

CHANGELOG.md
file/writer.go
tests/integration/dump_test.go
tests/integration/sync_test.go
tests/integration/test_utils.go
tests/integration/testdata/dump/001-entities-with-tags/expected.yaml
tests/integration/testdata/dump/001-entities-with-tags/kong.yaml

The expected behaviour for `deck dump` when using `--select-tag` is the following:
1. selected tags information should be summarized at the top of the configuration file inside the `_info` structure
2. selected tags must be removed from entity-level tags
Right now decK doesn't perform (2) consistently, stripping out selected tags from some entities, but not from some others. For example:
```
$ deck dump --select-tag test-tag --yes
_info:
defaults: {}
select_tags:
- test-tag
services:
- connect_timeout: 60000
enabled: true
host: mockbin.org
name: svc1
port: 80
protocol: http
read_timeout: 60000
retries: 5
routes:
- https_redirect_status_code: 301
name: r1
path_handling: v0
paths:
- /r1
preserve_host: false
protocols:
- http
- https
regex_priority: 0 …
```

fix: remove all selected tags when using dump

---

cmd/common.go
cmd/common_konnect.go
cmd/diff.go
cmd/konnect_diff.go
cmd/konnect_sync.go
cmd/reset.go
cmd/sync.go
diff/diff.go
diff/diff_helpers.go
diff/diff_helpers_test.go
tests/integration/diff_test.go
tests/integration/test_utils.go
tests/integration/testdata/diff/001-not-existing-workspace/kong.yaml
tests/integration/testdata/diff/001-not-existing-workspace/kong3x.yaml

fixes https://github.com/Kong/deck/issues/462

feat: mask environment variables from outputs

---

CHANGELOG.md
cmd/common.go
cmd/common_konnect.go
cmd/ping.go
tests/integration/test_utils.go

The konnectConfig object gets modified along the way in the process of building a Konnect client.
In order for this to work with the existing 'ping' logic, konnectConfig should be passed as a pointer

fix: ping fails with Konnect when using PAT

---

file/writer.go

This update adds additional information if a failure occurs when gathering referenced (or parent) resources; consumer, service, and route. The error message will contain the ID of the referenced resource that failed to be retrieved and include the plugin ID and name for easily identifying where the missing resource is referenced.

feat: enhance error messages during dump for plugins

---

diff/diff.go
tests/integration/diff_test.go
tests/integration/testdata/diff/001-not-existing-workspace/kong3x.yaml
tests/integration/testdata/diff/002-mask/initial.yaml
tests/integration/testdata/diff/002-mask/initial3x.yaml
tests/integration/testdata/diff/002-mask/kong.yaml
tests/integration/testdata/diff/002-mask/kong3x.yaml
tests/integration/testdata/diff/003-unmask/initial.yaml
tests/integration/testdata/diff/003-unmask/initial3x.yaml
tests/integration/testdata/diff/003-unmask/kong.yaml
tests/integration/testdata/diff/003-unmask/kong3x.yaml

This commit fixes a 'visual' regression introduced in https://github.com/Kong/deck/pull/463, which is making decK print full diff documents for 'create' and 'delete' actions. This can result in very
verbose output in case of configuration files
containing hundreds/thousands of resources.

fix: don't build diff doc for creates and deletes

---

diff/diff_helpers_test.go
file/readfile_test.go
tests/integration/diff_test.go

A testing cleanup.
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.Setenv

test: use `T.Setenv` to set env vars in tests

---

.github/workflows/integration-enterprise.yaml
crud/registry.go
file/kong_json_schema.json
go.mod
go.sum
konnect/consumer_group.go
state/consumer_group.go
state/consumer_group_consumers.go
state/consumer_group_plugin.go
tests/integration/sync_test.go
tests/integration/testdata/sync/015-consumer-groups/kong3x-initial.yaml
tests/integration/testdata/sync/016-consumer-groups-and-plugins/kong3x-initial.yaml
types/consumer_group.go
types/consumer_group_consumer.go
types/consumer_group_plugin.go

This PR:
* Add ConsumerGroup tags
* Add Konnect Update functionality for `ConsumerGroup` and `ConsumerGroupMember`
* Fix the index lookup of `ConsumerGroupConsumersCollection.Update`
* Fix the index lookup of `ConsumerGroupPluginsCollection.Update`
* Fix `consumerGroupConsumerCRUD.Update` for konnect+gateway support
* Fix `consumerGroupPluginCRUD.Update` to return the proper ID
* Add ConsumerGroup update tests for gateway and konnect
* Update go-kong to 0.35
* Update the CI enterprise matrix to use the latest patch release.

feat: add consumer group tags support

---

CHANGELOG.md
dump/dump.go

Right now decK error out when the Consumer Groups and Vaults list endpoints are hit and no license is present in the Gateway.
In such case, decK should continue its flow.

fix: do not error out on EE endpoints with no license

---

file/readfile.go
file/readfile_test.go
file/testdata/sharedworkspace/foo.yaml
file/testdata/sharedworkspace/meta.yaml

When running `deck sync` with multiple state files, either by passing multiple `-s` flags
(e.g. `-s foo.yaml -s bar.yaml`) or by passing a folder (e.g. `-s ./statefiles`), decK merges the whole configuration from all files and it fails the content validation if different `_workspace` entries are found. While this is good and expected by design, decK also fails in the following case:
```
$ cat foo.yaml
services:
- name: svc1
host: 1.example.com
tags:
- team-svc1
routes:
- name: r1
paths:
- /r1
$ cat meta.yaml
_format_version: "1.1"
_workspace: bar
```
The error from decK would be the following:
```
$ deck sync -s meta.yaml -s foo.yaml
Error: it seems like you are trying to sync multiple workspaces at the same time ([ bar]).
decK doesn't support syncing multiple workspaces at the same time, …
```

fix: workspaces validation with multiple files

---

cmd/common_konnect.go
konnect/list.go
utils/types.go

* fix: handle konnect runtime groups pagination properly
* fix http response error handling

fix: handle konnect runtime groups pagination properly

---

.github/workflows/release.yaml

fixes this warning: https://github.com/Kong/deck/actions/runs/4232904021/jobs/7353197221#step:4:20
docs: https://goreleaser.com/deprecations/#-rm-dist

chore(ci): update deprecated flag

---

file/readfile.go
file/readfile_test.go
file/testdata/parsebool/file.yaml

Currently Deck parses env variable in templates and renders it only as string, with other types it creates issues like having boolean flags for example. With this PR we can do this:
```yaml
services:
- name: svc1
host: mockbin.org
enabled: ${{ env "DECK_MOCKBIN_ENABLED" | toBool }}
```
Also i think we might want to do the same for Int / floats in the future

feat: add toBool function for template

---

file/readfile.go
file/readfile_test.go
file/testdata/parsefloat/file.yaml
file/testdata/parseint/file.yaml

Follow-up of https://github.com/Kong/deck/pull/867

feat: parsing numbers in templates

---

.github/workflows/integration-enterprise-nightly.yaml
.github/workflows/integration-enterprise.yaml
.github/workflows/integration-konnect.yaml
.github/workflows/integration.yaml
.github/workflows/test.yaml

Filter the push test condition to the main branch only, so that pull requests do not run duplicate tests for their pull and their branch push.
https://github.com/rainest/deck/actions/runs/4736968342 is a fork test of the main push condition.
This is an alternative to https://github.com/Kong/deck/pull/894 that does not change deck behavior, on the working hypothesis that there's a race between the two jobs for Konnect interactions.
https://github.com/Kong/deck/actions/runs/4736946073 succeeded on all 5 runs, which is promising.

chore: filter test action conditions

---

tests/integration/sync_test.go
tests/integration/test_utils.go

Run all >= 3.0 tests for Konnect as well to improve coverage.

tests: run all >=3.0 tests against Konnect

---

CHANGELOG.md
diff/diff.go
diff/order.go
diff/order_test.go
tests/integration/sync_test.go
tests/integration/test_utils.go
tests/integration/testdata/sync/020-same-names-altered-ids/1-before.yaml
tests/integration/testdata/sync/020-same-names-altered-ids/2-before.yaml
tests/integration/testdata/sync/020-same-names-altered-ids/3-before.yaml
tests/integration/testdata/sync/020-same-names-altered-ids/desired.yaml
tests/integration/testdata/sync/021-update-with-explicit-ids/after.yaml
tests/integration/testdata/sync/021-update-with-explicit-ids/before.yaml
types/consumer.go
types/core.go
types/postProcess.go
types/route.go
types/service.go

This adds an additional step to the `diff.Syncer`'s `diff` producer - `deleteDuplicates`. Its purpose is to clean up the entities in the **current** state that have duplicates with the same names in the **target** state before proceeding with updates/creates and regular deletes. Without that additional step, it's not possible to perform sync in which the IDs of entities are changed while their names are kept between syncs. 
An actual use-case that is the motivation for this change is Kong Ingress Controller where we recently started assigning entities' IDs explicitly. Without this change, existing setups break when KIC is upgraded from the version not setting the IDs to the new one because of breaking the uniqueness constraints of Services, Routes, and Consumers.
The added test cases …

feat: allow updating entities' IDs while keeping their names

---

file/readfile.go
file/readfile_test.go
file/testdata/file.yaml

We want to extract Lua code from `kong.yaml` file for two reasons:
1. Better syntax highlight in the IDE for .lua files
2. Write unit tests for the functions
So, we would like to have a setup like that:
**kong.yaml**
```yaml
---
plugins:
- name: pre-function
config:
log: |
${{ env "DECK_FILE_LOG_FUNCTION" | indent 8 }}
```
**file_log.lua**
```lua
function parse_traceid(str)str = string.sub(str,1,8)
local uint = 0
for i = 1, #str do
uint = uint + str:byte(i) * 0x100^(i-1)
end
return string.format("%.0f", uint)
end
kong.log.set_serialize_value("trace_id", parse_traceid(ngx.ctx.KONG_SPANS[1].trace_id))
kong.log.set_serialize_value("span_id", parse_traceid(ngx.ctx.KONG_SPANS[1].span_id))
```
However, without the `indent` function, it is not possible to convert the yaml …

feat: Add indent function to support multi-line content

---

tests/integration/sync_test.go
tests/integration/testdata/sync/022-update-with-explicit-ids-with-no-names/after.yaml
tests/integration/testdata/sync/022-update-with-explicit-ids-with-no-names/before.yaml
types/route.go
types/service.go

As both `Service` and `Route` names are allowed to be empty, we have to account for this case in the code detecting duplicates and short-circuit when the target entity has no name to prevent panics.
Fixes #944.

fix: handle missing service and route names detecting duplicates

---

utils/types.go

feat(proxy): honor the proxy environment variables

---

.github/workflows/validate-kong-release.yaml

This commit adds a workflow with two inputs to supply the Kong Gateway image and decK branch to test against.

chore: add a GitHub action for validating Kong Gateway images

---

.github/workflows/validate-kong-release.yaml

This commit adds the license to allow for enterprise testing and also shortens the run name to make it more readable via the actions tab.

chore: add license for Kong Gateway release validation

---

cmd/convert.go
cmd/file.go
cmd/root.go

desired structure:
```
- version     Print the decK version
- completion  Generate completion script
- help        Help about any command
​
- file        decK file operations
- add-tags     Adds tags to objects in a decK file
- list-tags    Lists current tags to objects in a decK file
- merge        Merges multiple decK files into one
- openapi2kong Convert OpenAPI files to Kong's decK format
- patch        Applies patches on top of a decK file
- remove-tags  Removes tags from objects in a decK file
- convert      Convert files from one format into another format
- render       renders a final decK file as it would be synced (for local diffs)
- validate     ==> alias for usability, since it does both file+online
- kong        online operations
- diff         Diff the current entities in …
```

chore: refactor the cli command structure

---

cmd/file.go
cmd/file_addplugins.go
cmd/file_addtags.go
cmd/file_listtags.go
cmd/file_merge.go
cmd/file_openapi2kong.go
cmd/file_patch.go
cmd/file_removetags.go

Follow-up PR to https://github.com/Kong/deck/pull/939. 
Mirrors changes going into the docs in https://github.com/Kong/docs.konghq.com/pull/5819 (minus some formatting so that it doesn't break anything).
Cleaning up new `deck file` commands for readability and consistency, plus better generated output to the doc site.

docs(apiops): Clean up command text for new file commands

---

go.mod
go.sum

adds a warning when a patch command receives a file without selectors set

chore(deps): bump go-apiops to v0.1.20

---

tests/integration/diff_test.go
tests/integration/sync_test.go
tests/integration/testdata/sync/023-create-and-update-certificate-with-snis/initial.yaml
tests/integration/testdata/sync/023-create-and-update-certificate-with-snis/update.yaml
types/certificate.go
types/core.go

As Konnect does not support the API sugar that allows specifying `SNIs` on `PUT /certificates`, we should not fill them when an update of a certificate is performed. 
It's still required for regular Kong Gateways as they would treat empty `SNIs` in a certificate as a signal to remove any existing `SNIs` associated with a certificate.

feat: handle certificates:snis relation for Konnect

---

CHANGELOG.md
file/builder.go
file/writer.go
state/builder.go
state/consumer.go
state/consumer_test.go
tests/integration/sync_test.go
tests/integration/testdata/sync/024-consumers-with-custom_id-and-username/kong3x.yaml
types/consumer.go

Right now, when a consumer has the `username` equal to the `custom_id` of another consumer, decK fails because of the way the consumers are handled in the internal in-memory DB.
```
consumers:
- custom_id: foo
id: ce49186d-7670-445d-a218-897631b29ada
username: Foo
- custom_id: bar
id: 7820f383-7b77-4fcc-af7f-14ff3e256693
username: foo
```
```
$ deck sync
Error: inserting consumer into state: inserting consumer Foo: entity already exists
```
This commit fixes this defect by modifying the way consumers are looked up in the in-memory DB.

fix: correct consumers handling when custom_id is used

---

cmd/root.go

Fixing a small typo. Since it's a global flag, it shows up in every command.

fix: Typo in global konnect-token-file flag

---

.gitattributes

Prevent showing diffs of `file/kong_json_schema.json` since it contains generated.

chore: mark file/kong_json_schema.json as generated code

---

convert/testdata/5/output-expected.yaml
convert/testdata/6/output-expected.yaml
convert/testdata/7/output-expected.yaml
utils/constants.go
utils/defaulter_test.go

In the past decK had to set the default value of the `strip_path` field to [false](https://github.com/Kong/deck/blob/v1.26.0/utils/constants.go#L22) because of some limitation in the library used for defaults injection: this was a workaround to allow this field to be set to `false`. Then, if the field was not set in the configuration, the field was then turned into `true` at runtime via inspection of the Kong Admin API.
This commit changes the decK default for the `strip_path` field to `true`, since now the underlying library has fixed the issue that triggered this workaround in the first place.

fix: set default strip_path to true

---

cmd/file_addplugins.go

Someone filed a PR to fix this in the docs, but the source is here. Fixing source so that we don't pull it in again.
https://github.com/Kong/docs.konghq.com/pull/5940

fix(docs) Remove errant comma from CLI example

---

cmd/file_removetags.go

Parallel to docs PR: https://github.com/Kong/docs.konghq.com/pull/6037
Examples are telling users to run `go-apiops`, which is only supposed to be used for dev/testing. Changing that to the standard `deck file`.

fix(docs/cmd) Change go-apiops in remove-tags examples to deck file

---

cmd/file_render.go

The existing description for `deck file render` doesn't currently provide any detail on what the command does or how to use it. 
I was trying to test it out and couldn't even figure out how it was supposed to work, since there's no input file flag or example. 
Found the info I needed on Slack here, and based the update on that: https://kongstrong.slack.com/archives/C04349E4KRC/p1690921140291889
❗ I did run into one potential issue while testing: this command doesn't warn you when overwriting existing files, like `deck dump` or others do. Is that intentional?

docs(cli): Add a long description for file render

---

go.mod
go.sum

Fixes several issues;
- fix(tags): the entitylist for tags was missing acl-groups
- fix(oas): allow overriding route.strip_path
- fix(oas): use google's UUID generator for UUID generation instead of an unmaintained library
Full changelog: https://github.com/Kong/go-apiops/releases/tag/v0.1.21

chore(deps): bump go-apiops to 0.1.21

---

state/consumer.go
tests/integration/sync_test.go
tests/integration/testdata/sync/024-consumers-with-custom_id-and-username/kong3x-reverse-order.yaml

This commit corrects a bug preventing consumers with equal `Username` and `CustomID` to always be correctly handled by decK.
For example, syncing the following state file works as expected:
```
consumers:
- username: TestUser
- username: OtherUser
custom_id: TestUser
```
```
$ deck sync
creating consumer OtherUser
creating consumer TestUser
Summary:
Created: 2
Updated: 0
Deleted: 0
```
But syncing the following state file (same content as the first one, but with consumers in reverse order) doesn't work:
```
consumers:
- username: OtherUser
custom_id: TestUser
- username: TestUser
```
```
$ deck sync
Error: building state: inserting consumer TestUser: entity already exists
```
This commit is making sure this bogus inconsistency …

fix: correct inconsistency for multiple consumers with custom_id fields

---

cmd/file_openapi2kong.go
go.mod
go.sum

OAS conversion updates:
- changes generated names to be more Inso like
- adds an option to skip generating ID's

deps(apiops): bump apiops to v0.1.22

---

cmd/file_openapi2kong.go
go.mod
go.sum

This reverts commit ccb159e6c7ecc797a8c228b97619e03b4462de7e.

Revert "deps(apiops): bump apiops to v0.1.22 (#1040)"

---

cmd/file_addplugins.go
cmd/file_addtags.go
cmd/file_listtags.go
cmd/file_merge.go
cmd/file_openapi2kong.go
cmd/file_patch.go

chore(cli): add examples

---

cmd/common.go
cmd/file_addplugins.go
cmd/file_addtags.go
cmd/file_convert.go
cmd/file_listtags.go
cmd/file_merge.go
cmd/file_openapi2kong.go
cmd/file_patch.go
cmd/file_removetags.go
cmd/file_render.go

feat(analytics): add analytics for local operations

---

cmd/file_openapi2kong.go

fixes https://github.com/Kong/go-apiops/issues/98

chore(cli): document compatibility to be Kong 3.x

---

cmd/file_patch.go

requires apiops > 0.1.22 for this pr: https://github.com/Kong/go-apiops/pull/100
values were specified on the CLI as `--value 'key:value'`, and arrays could not. But arrays
were possible in the patch file format. This adds the format `--value '[1,2,3]'` to specify the arrays on the CLI as well.

feat(patch): allow arrays to be specified on the CLI

---

.gitignore
cmd/file_convert.go
cmd/gateway_dump.go

2 Cobra commands were generated; deprecated, and current. Both would point to the same golbal variable.
The bug is that Cobra sets the defaults when CREATING the command not when parsing. This means that the last command created would set the global defaults, and hence overwrite the ones from the other command.
Introduced in #962
Jira: DECK-156

fix(cli): deprecated commands default to kong.yaml

---

cmd/file_convert.go
cmd/gateway_diff.go
cmd/gateway_dump.go
cmd/gateway_ping.go
cmd/gateway_reset.go
cmd/gateway_sync.go
cmd/gateway_validate.go
tests/integration/diff_test.go

This is ugly and inconsistent, but not breaking.

fix(cli): move deprecation warnings to stderr

---

CHANGELOG.md

Make it more explicit that they did not only move, but also had changes

chore(changelog): clarify 2.8 command changes in changelog

---

cmd/common.go
cmd/common_konnect.go

This commit removes the logic to fetch the Konnect version from Konnect API and it simply hardcodes it. The Konnect version is used only to evaluate and decide which format_version to expect or dump in state files. Since Konnect only uses '_format_verion: 3.0', and since Konnect always uses the latest Kong version, then we can simply hardcode the Konnect version and avoid an unnecessary network call

fix: use hardcoded Konnect version instead of retrieving it

---

.golangci.yml
Makefile
cmd/root.go
file/codegen/main.go
file/reader_test.go
file/readfile.go
file/writer.go
konnect/error.go
tests/integration/lint_test.go

This PR makes `staticheck`'s exclude rules narrower by only ignoring the `rand.` regex (this is problematic to solve - not impossible - because we're using `rand.Seed()` which [is now deprecated](https://pkg.go.dev/math/rand#Seed) in favor of `New(NewSource(seed))` which returns a variable and doesn't affect the global behavior).

chore: enable linter rules for deprecated code and fix offending lines

---

.github/workflows/integration-konnect.yaml
tests/integration/ping_test.go
tests/integration/test_utils.go

Related issue: https://github.com/Kong/deck/issues/1100
This PR mostly unblocks the CI so that it doesn't fail anymore. We can remove the konnect basic auth related functionality or fix it in a separate PR.

tests: fix konnect integration tests

---

.github/workflows/integration-enterprise.yaml
.github/workflows/integration-konnect.yaml
.github/workflows/integration.yaml
.github/workflows/test.yaml
.github/workflows/validate-kong-release.yaml

Use https://github.com/Kong/kong-license/ instead of manually updated secret. 🤖 
Also while at it, change the order of steps in tests to utilize Go cache. Without this change repo is not checked out when go is being set up:
```
Restore cache failed: Dependencies file is not found in /home/runner/work/deck/deck. Supported file pattern: go.sum
```

ci: use license action

---

.github/workflows/integration-enterprise.yaml
.github/workflows/integration-konnect.yaml
.github/workflows/integration.yaml
.github/workflows/test.yaml

This PR will limit the concurrency of CI jobs to 1, running only on the most recent commit in PR branch and cancelling old (still running) jobs. This prevents queueing on the CI.

ci: don't run more than once per PR branch

---

go.mod
go.sum

fixes a bug in openapi2kong with [port parsing](https://github.com/Kong/go-apiops/pull/105)

bump(go-apiops): bump to v0.1.24, bugfixes

---

.github/workflows/integration-enterprise.yaml
.github/workflows/validate-kong-release.yaml

This change is required to accommodate the forthcoming work in https://github.com/Kong/kong-license/pull/25
That work will change kong-license such that the license is sourced directly from 1Password, rather than it being sourced from Pulp using credentials from 1Password (as is the case today). Meaning that workflows needing to run Kong/kong-license's will require 1P credentials instead of the Pulp password.
This work is a necessary step in the deprecation of Pulp aka [KAG-2247](https://konghq.atlassian.net/browse/KAG-2247) / [KAG-3254](https://konghq.atlassian.net/browse/KAG-3254).
Leaving the Pulp password for now so that https://github.com/Kong/kong-license/pull/25 can be merged *after* this PR.
[KAG-2247]: https://konghq.atlassian.net/browse/KAG-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

chore(gha): preemptively add 1p creds

---

cmd/file_convert.go
cmd/gateway_diff.go
cmd/gateway_dump.go
cmd/gateway_ping.go
cmd/gateway_reset.go
cmd/gateway_sync.go
cmd/gateway_validate.go

2 commits;
- describe changes when switching to new commands
- diplay message when reading from stdin
EDIT: 2nd commit moved here: https://github.com/Kong/go-database-reconciler/pull/17

chore(cli): improve warnings

---

cmd/file_openapi2kong.go
go.mod
go.sum

Adds generating OIDC plugins from OpenAPI Security directives
This also makes go-apiops commands update the cli warnings, hence merging this PR should be aligned with;

deps(go-apiops): bump to 0.1.26, adding O2K security

---

.github/workflows/test.yaml

This reverts commit bfd04d22acd8e6e9d743fcac22871ee7c160b471.
The retry action doesn't solve the issue, but did introduce CI warning wrt Node 16 being used. Hence reverting.

Revert "chore(ci): wrap codecov upload in a retry (#1178)"

---

kong2kic/route.go
kong2kic/upstream.go

Fixes 3 issues in kong2kic:
1. Handles nil pointer error when service port is not specified and output style is Gateway API
2. Handles the case in which no HTTP method is specified in a Route
3. Add annotation from service to upstream only when relationship is found.

Handle nil error when port not defined in service with Gateway API.

---

cmd/file_merge.go

The file merge command example says `deck file patch`, so fixing that.

Fix(cmd/docs): Correct file_merge example

---

cmd/file_render.go
convert/convert_test.go
tests/integration/render_test.go
tests/integration/test_utils.go
tests/integration/testdata/render/001-mocked-env/expected.yaml
tests/integration/testdata/render/001-mocked-env/input.yaml
tests/integration/testdata/render/002-populated-env/expected.yaml
tests/integration/testdata/render/002-populated-env/input.yaml

Resolves #1207 
By default `deck file render` mocks the values of `DECK_` env vars. This was intentional as to support rendering a full configuration in environments where all values are not present (ex: CI systems).  This PR adds a flag for `deck file render`, `--populate-env-vars` with a default of `false`.  The flag is written in the affirmative case while the `false` default prevents breaking previous default behavior. Users interested in populating the env vars must set `--populate-env-vars` to enable the behavior.
```
DECK_ECHO_DOWNSTREAM=true DECK_HEADER_NAME=X-Flag ./deck file render ~/kong/tmp/deck-file-render-1207.yaml
plugins:
- config:
echo_downstream: false
generator: uuid
header_name: DECK_HEADER_NAME
enabled: true
name: correlation-id
protocols:
- …
```

feat: Add flag to render allowing DECK_ env var processing

---

cmd/common.go
cmd/gateway_validate.go
utils/utils.go
validate/validate.go

decK used to fetch the running Kong version in order to gate route regex patterns validation. This is problematic in the case users don't have access to the `/` endpoint, which is the one used to fetch the version of the runtime.
This commit removes the need of fetching the Kong version entirely by relying on the `_format_version` field from the config file instead.

fix: do not fetch kong version when running `validate`

---

convert/convert.go
convert/convert_test.go

Followup to #1206 
The previous implementation did not handle Consumer Groups, which is a requirement for the customer

fix: auto-generate rla namespace when using Consumer Groups

---

kong2kic/route.go

HTTPRoute's header match rules were not sorted and that caused tests to fail. 
This PR introduces the sorting step so that each run produces the same output.

fix: make KIC v2 Gateway API v2 config generation deterministic

---

CHANGELOG.md
go.mod
go.sum
tests/integration/diff_test.go
tests/integration/testdata/diff/005-no-diff-target/kong.yaml

- make lookups for consumer-group's consumers more performant
- properly expand ipv6 targets avoid misleading diffs

chore: bump go-database-reconciler dependency

---

.github/workflows/codeql-analysis.yml
.github/workflows/integration-enterprise.yaml
.github/workflows/integration-konnect.yaml
.github/workflows/integration.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
.github/workflows/validate-kong-release.yaml

This would fix issue #1282.
Fetching the version directly from go.mod would help us to maintain consistency in the project and the released versions.

#1282 Updated git workflows to use go.mod for go versions

---

.github/workflows/integration-enterprise.yaml
.github/workflows/integration.yaml

Latest images may have bugs and thus, lead to failing tests, even if the submitted changes have no connection with the test.
Ignoring them from the CI for clean builds.
This change is similar to: https://github.com/Kong/go-database-reconciler/commit/c70e4ecf881c99043fee22cf08d23b03643659d3

CI: Ignoring errors from latest images to account for flaky tests

---

cmd/root.go

This fixes issue #1313 and makes the flag behaviour consistent across tty and non-tty.
The attached image shows the changed behaviour.
Now, the non-tty output also comes up as colored by default, same as tty output. This can be overridden by passing the `--no-color` flag.
I have a doubt though.
If our customers pass the deck output to a non-tty (may be a file), this can cause things to break if `--no-color` is not passed, as the colorised output may cause formatting issues in a file.
Is this doubt valid?
Should I check for non-tty environments separately and handle this, if this is indeed a valid usecase?
@GGabriele @mheap

Fixed --no-color flag behaviour in non-tty environments

---

cmd/file_patch.go

The command intends to patch input files either via selector-value flags or patch file arguments. The change ensures that at least one of these is present, but not both at the same time. Till now, the command accepted patches from flags and patch files at the same time, but ignored the patches passed via flags. This was a confusing behaviour for customers.
Fix #1130
@rspurgeon I have created a new issue for patch file validation [here](https://github.com/Kong/deck/issues/1341).
We can discuss its feasibility and usecase there. For this particular issue (#1130), I felt erroring out with a proper reasoning given to user should be the best way to move forward.

fix: validate presence of flags and args in file patch command

---

go.mod
go.sum

This ensures that fields from traditional routes do not propagate into expression routes in case
kong gateway version is < 3.7.0
This change goes along with
https://github.com/Kong/go-database-reconciler/pull/118/files

fix: updated go-database-reconciler library.

---

.github/workflows/integration-enterprise.yaml
.github/workflows/integration.yaml

Add 3.7 to test matrix.
Removed EOLd versions from test matrix, as listed in https://docs.konghq.com/gateway/latest/support-policy/#older-versions

ci: add Kong 3.7 and remove EOLd versions from CI

---

.github/workflows/integration-enterprise.yaml
.github/workflows/validate-kong-release.yaml

This gets rid of 
```
Warning: Input 'password' has been deprecated with message: pulp no longer used, only 'op-token' is needed
```
warning in CI workflow runs.

chore(ci): don't use deprecated password field with kong-license action

---

go.mod
go.sum

This version of go-database-reconciler has the fix that ensures that plugins are not shown as global
if they have a consumer group attached.
Earlier, they were wrongly shown as global, despite the actual associations working fine.
Fixes #1005
GDR PR with the fix: https://github.com/Kong/go-database-reconciler/pull/134

chore: updated go-database-reconciler to v1.14.5

---

cmd/common_konnect.go
tests/integration/test_utils.go

- chore: creating a retryable kong client for tests to account for rate-limit errors
- fix: added retry and backoff logic in Konnect authentication layer to account for rate-limit errors during authentication.
Fixes [#1364](https://github.com/Kong/deck/issues/1364)

fix: creating a retryable kong client for tests and retry logic in konnect authentication for CI rate-limit errors

---

kong2tf/generate_resource.go
kong2tf/generate_resource_test.go

This PR fixes kong2tf panics when a field is an empty list:
```
➜ cat kong.yaml | deck file kong2tf
panic: runtime error: index out of range [-1]
goroutine 1 [running]:
github.com/kong/deck/kong2tf.endList({0x2b3dd00, 0x0, 0x17d555a?}, 0xc00057a010?)
github.com/kong/deck/kong2tf/generate_resource.go:357 +0xaa
github.com/kong/deck/kong2tf.outputList({0xc00054e6d8, 0x12}, {0xc000563f30?, 0xc?}, {0x2b3dd00, 0x0, 0x0}, 0x2)
github.com/kong/deck/kong2tf/generate_resource.go:350 +0x225
github.com/kong/deck/kong2tf.output({0xc00054e6d8, 0x12}, 0xc000567170, 0x2, 0x1, {0x1a93448, 0x1}, 0xc0005bd868)
github.com/kong/deck/kong2tf/generate_resource.go:288 +0x5c5
github.com/kong/deck/kong2tf.outputHash({0xc00054e6d8, 0x12}, {0xc000563f78, 0x6}, 0xc000567170, 0x1, 0x10?, {0x1a93448, 0x1}, …
```

Fix panic when field is an empty list

---

CHANGELOG.md

Last release's changelog wasn't added in the Changelog.md but directly drafted in the release.
Added it here for parity's sake.

chore: added missing changelog entry for v1.40.2 release

---

kong2tf/builder_default_terraform.go
kong2tf/testdata/ca-certificate-output-expected.tf
kong2tf/testdata/certificate-sni-output-expected.tf
kong2tf/testdata/consumer-acl-output-expected.tf
kong2tf/testdata/consumer-basic-auth-output-expected.tf
kong2tf/testdata/consumer-group-output-expected.tf
kong2tf/testdata/consumer-group-plugin-output-expected.tf
kong2tf/testdata/consumer-hmac-auth-output-expected.tf
kong2tf/testdata/consumer-jwt-output-expected.tf
kong2tf/testdata/consumer-jwt-output-with-imports-expected.tf
kong2tf/testdata/consumer-key-auth-output-expected.tf
kong2tf/testdata/consumer-no-auth-output-expected.tf
kong2tf/testdata/consumer-plugin-output-expected.tf
kong2tf/testdata/global-plugin-oidc-output-expected.tf
kong2tf/testdata/global-plugin-rate-limiting-output-expected.tf
kong2tf/testdata/route-output-expected.tf
kong2tf/testdata/route-plugin-output-expected.tf
kong2tf/testdata/service-output-expected.tf
kong2tf/testdata/service-plugin-output-expected.tf
kong2tf/testdata/upstream-target-output-expected.tf
kong2tf/testdata/vault-output-expected.tf

Type constraints in quotes was required in Terraform 0.11 and earlier, but that form is now deprecated and will be removed in a future version of Terraform. For example:
```
variable "control_plane_id" {
type = "string"
default = "YOUR_CONTROL_PLANE_ID"
}
```
should be
```
variable "control_plane_id" {
type = string
default = "YOUR_CONTROL_PLANE_ID"
}
```
if the quotes are present, an error is shown during terraform apply.

Remove quoted type constraints

---

validate/validate.go

Online validation via deck gateway validate now supports validating vaults as well.

feat: added validation for vault entities.

---

CHANGELOG.md
README.md
cmd/gateway_validate.go
tests/integration/validate_test.go
validate/konnect_compatibility.go
validate/konnect_compatibility_test.go

Earlier, if konnect control plane information was passed via cli flags, online validation for Konnect was failing. This change fixes the issue.

fix: konnect cli flags getting considered for online validation.

---

kong2tf/generate_resource.go
kong2tf/generate_resource_test.go

[`generateImportKeys`](https://github.com/Kong/deck/blob/f6f1880b299931c9e2afa47f1584a0f116d1f608/kong2tf/generate_resource.go#L212-L227) generated terraform's import keys. The test assumes that the keys are always in the same order but they are not as they are generated using a `map` which does not yield the same order each time it's being looped over.
This PR fixes that by sorting the keys on each marshal operation.

fix: make terraform imports keys order deterministic

---

.github/workflows/integration-konnect.yaml

Konnect integration tests rely on static identifiers in test files so they cannot be run in parallel.
This PR makes them run in sequence.

ci: do not run Konnect integration tests in parallel

---

kong2tf/generate_resource.go
kong2tf/generate_resource_test.go

Adjusted multiline string formatting in terraform resource generation. Make sure `<<EOF` and `EOF` are correctly placed.
Expanded current testing to verify multiline strings.
Fixes https://konghq.atlassian.net/browse/FTI-6414.

fix: adjust multiline string formatting in resource generation

---

cmd/file_convert.go
cmd/utils.go
tests/integration/file_convert_test.go
tests/integration/test_utils.go
tests/integration/testdata/file-convert/001-kong-gateway-config/kong-gateway-2-x.yaml
tests/integration/testdata/file-convert/001-kong-gateway-config/kong-gateway-3-x.yaml

fix: improve error messaging when mandatory flag is missing in file convert (#1429)
When mandatory flags for file convert are missing, the error message is not helpful. In this commit, we have added additional validation to communicate more details in the message.
We have made use of the `PreRunE` function in cobra to validate the input passed in `to` flag - since local flags are not inherited by subcommands.
This PR validates the `from` and `to` flags only. This is because all the other flags have valid default values which get used when not specified.
How I have tested my changes:
To do:

fix: improve error messaging when mandatory flag is missing in file convert (#1429)

---

go.mod
go.sum
tests/integration/testdata/dump/001-entities-with-tags/expected.yaml
tests/integration/testdata/dump/001-entities-with-tags/expected30.yaml
tests/integration/testdata/dump/001-entities-with-tags/expected381.yaml

chore(deps): Bump go-database-reconciler to 1.18.1
This fixes https://github.com/Kong/deck/issues/1488
PR on go-database-reconciler for reference: https://github.com/Kong/go-database-reconciler/pull/165
Some indirect dependencies have been bumped as well.
Changelog: https://github.com/Kong/go-database-reconciler/releases/tag/v1.18.1

chore(deps): Bump go-database-reconciler to 1.18.1

---

.github/workflows/release.yaml

This is need so that goreleaser and docker action can read the repository contents and create/upload artifacts.

chore: added permissions in release workflow

---

cmd/common.go
cmd/common_konnect.go
cmd/gateway_apply.go
cmd/gateway_diff.go
cmd/gateway_reset.go
cmd/gateway_sync.go
go.mod
go.sum
tests/integration/apply_test.go
tests/integration/testdata/apply/005-foreign-keys-services/expected-state.yaml
tests/integration/testdata/apply/005-foreign-keys-services/plugin-01.yaml
tests/integration/testdata/apply/005-foreign-keys-services/service-01.yaml
tests/integration/testdata/apply/006-foreign-keys-routes/expected-state.yaml
tests/integration/testdata/apply/006-foreign-keys-routes/plugin-01.yaml
tests/integration/testdata/apply/006-foreign-keys-routes/route-01.yaml
tests/integration/testdata/apply/007-update-existing-entity/expected-state-01.yaml
tests/integration/testdata/apply/007-update-existing-entity/expected-state-02.yaml
tests/integration/testdata/apply/007-update-existing-entity/service-01.yaml
tests/integration/testdata/apply/007-update-existing-entity/service-02.yaml

The existing `deck gateway apply` command works when applying a resource for the first time, but error due to duplicate entities when trying to update the resource.
This PR moves the partial apply logic to `go-database-reconciler` (https://github.com/Kong/go-database-reconciler/pull/182) and removes the `isPartialApply` logic from decK. This also removes the license checks that were previously added for Consumer Group fetching as GDR now handles this.

Fix `deck gateway apply`

---

cmd/common.go
cmd/root.go
go.mod
go.sum
tests/integration/sync_test.go
tests/integration/test_utils.go
tests/integration/testdata/sync/036-degraphql-routes/kong-complex-query.yaml
tests/integration/testdata/sync/036-degraphql-routes/kong-fake.yaml
tests/integration/testdata/sync/036-degraphql-routes/kong.yaml

Changes added:
degraphql_routes can be created via deck on Kong GW or Konnect.

feat: added support for degraphql_routes

---

cmd/common.go
cmd/gateway_diff.go
cmd/gateway_dump.go
cmd/gateway_sync.go
go.mod
go.sum
tests/integration/dump_test.go
tests/integration/reset_test.go
tests/integration/sync_test.go
tests/integration/test_utils.go
tests/integration/testdata/sync/037-consumer-group-policy-overrides/kong34x-no-info.yaml
tests/integration/testdata/sync/037-consumer-group-policy-overrides/kong34x.yaml
tests/integration/testdata/sync/037-consumer-group-policy-overrides/kong38x-no-info.yaml
tests/integration/testdata/sync/037-consumer-group-policy-overrides/kong38x.yaml
tests/integration/testdata/sync/037-consumer-group-policy-overrides/kong39x-no-info.yaml
tests/integration/testdata/sync/037-consumer-group-policy-overrides/kong39x.yaml

Proposal Draft: https://konghq.atlassian.net/wiki/spaces/A/pages/4357751187/Consumer+Group+Policy+Overrides+with+Deck
Related GDR changes: https://github.com/Kong/go-database-reconciler/pull/191

feat: adding consumer-group policy overrides support in deck

---

tests/integration/dump_test.go
tests/integration/sync_test.go
tests/integration/testdata/dump/001-entities-with-tags/expected310.yaml

Found the errors from here: https://github.com/Kong/deck/actions/runs/13301511069/job/37143666843
3.10 adds new config property `wasm_metrics` for prometheus plugin. This change in schema was causing failures with the 3.10 release candidate.
This branch fixes those failures. Tests are fixed as verified from here: https://github.com/Kong/deck/actions/runs/13301685469/job/37144135345

tests: fixed integration tests for gw 3.10 rc

---

cmd/common.go
cmd/gateway_diff.go
cmd/gateway_dump.go
cmd/gateway_sync.go
cmd/utils.go
tests/integration/sync_test.go
tests/integration/testdata/sync/038-skip-consumers-with-cgs/base.yaml
tests/integration/testdata/sync/038-skip-consumers-with-cgs/consumers.yaml

This flag was earlier enabled on dump command.
We are adding it to sync and diff commands too
as it provides performance benefits in case an
enterprise has thousands of consumers per group.
It ensures that list_consumers=false while
querying a consumer-group. This is beneficial for
enterprise customers who sync consumers separately on a different cadence 
but require frequent changes in other entity configurations. 
Not listing consumers leads to a boost in performance in such cases.
Related changes:
https://github.com/Kong/go-database-reconciler/pull/159
https://github.com/Kong/go-kong/pull/494
Why was this change necessary?
Check linked FTI: https://konghq.atlassian.net/browse/FTI-6183
More info: https://kongstrong.slack.com/archives/C07AQH7SAF8/p1736409331920239
For #1524

feat: added --skip-consumers-with-consumer-groups to sync and diff commands

---

.golangci.yml
convert/convert_test.go
tests/integration/diff_test.go
tests/integration/dump_test.go
tests/integration/file_convert_test.go
tests/integration/lint_test.go
tests/integration/render_test.go
tests/integration/sync_test.go
tests/integration/validate_test.go

Add https://github.com/Antonboom/testifylint to golangci-lint to catch common testify mistakes.

ci: add testifylint to golangci-lint config

---

CHANGELOG.md
README.md

go-database-reconciler diff: https://github.com/Kong/go-database-reconciler/compare/v1.20.3...v1.22.0
go-kong diff: https://github.com/Kong/go-kong/compare/v0.63.0...v0.64.1
Apart from the changes listed in changelog, the following would be shipped alongside:
- https://github.com/Kong/deck/pull/1550

chore: added changelog for v1.46.0

---

tests/integration/sync_test.go

Some tests for partials seem to be failing in konnect since a new property `timeout` is present in the response. ([link](https://github.com/Kong/deck/actions/runs/14245134517/job/39966070393?pr=1585) to a failing job)
The same is not present in Kong Enterprise GW.
So, I've separated the tests, and included the new property in the konnect tests.

fix: tests failing due to missing timeout key

---

CHANGELOG.md
README.md

Changes included in this release:
- Fix false diff for ip-restriction plugin
https://github.com/Kong/deck/pull/1585
https://github.com/Kong/go-database-reconciler/pull/240
- Fix non json output being printed on stdout
https://github.com/Kong/deck/pull/1589
https://github.com/Kong/go-database-reconciler/pull/242
- Fix integration tests for partials in konnect
https://github.com/Kong/deck/pull/1586
Diff for GDR versions: https://github.com/Kong/go-database-reconciler/compare/v1.22.1...v1.22.3

chore: add changelog for v1.46.2

---

go.mod
go.sum
tests/integration/sync_test.go
tests/integration/testdata/diff/004-no-diff-plugin/protocol-initial-order-plugins.yaml
tests/integration/testdata/diff/004-no-diff-plugin/protocol-reordered-plugins.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/1_1/kong-consumer-groups-via-ids.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/1_1/kong-consumer-groups-via-names.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/1_1/kong-consumers-via-ids.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/1_1/kong-consumers-via-names.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/1_1/kong-routes-via-ids.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/1_1/kong-routes-via-names.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/1_1/kong-services-via-ids.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/1_1/kong-services-via-names.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/kong3x-consumer-groups-via-ids.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/kong3x-consumer-groups-via-names.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/kong3x-consumers-via-ids.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/kong3x-consumers-via-names.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/kong3x-routes-via-ids.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/kong3x-routes-via-names.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/kong3x-services-via-ids.yaml
tests/integration/testdata/sync/041-plugins-nested-foreign-keys/kong3x-services-via-names.yaml

This change updates gdr version to v1.22.4
Here, we have relaxed the restrictions
added in an earlier deck version to error
out in case of foreign keys under a plugin
config. Now, errors come up only if same
type of entity is nested under an entity.
This change has also fixed the resolution
of foreign keys in case names are used,
instead of IDs.

fix: fixed foreign key reference under plugin config

---

CHANGELOG.md
README.md

GDR changes: https://github.com/Kong/go-database-reconciler/compare/v1.22.3...v1.22.4
go-kong changes: https://github.com/Kong/go-kong/compare/v0.65.0...v0.65.1
Deck changes: https://github.com/Kong/deck/compare/v1.46.2...main

chore: release prep for v1.46.3

---

CHANGELOG.md
README.md

All Changes:
go-apiops: https://github.com/Kong/go-apiops/compare/v0.1.41...v0.1.42
gdr: https://github.com/Kong/go-database-reconciler/compare/v1.22.4...v1.22.5
deck: https://github.com/Kong/deck/compare/v1.46.3...main

chore: release prep for v1.47.0

---

tests/integration/sync_test.go

Some tests for plugins were accidentally removed while reverting https://github.com/Kong/deck/pull/1608/files#diff-b09c72ddce91eda1770990ad2744a3867eb59e006e6842fc4d01b8d3ce5eec77.
Adding them back.

tests: add missing tests for plugin nested foreign keys back

---

go.mod
go.sum
tests/integration/apply_test.go
tests/integration/testdata/apply/008-custom-entities/initial-state.yaml
tests/integration/testdata/apply/008-custom-entities/partial-update.yaml

In this PR, we are bumping Go database reconciler and adding integrations tests to run `gateway apply` for custom entities.
PR on GDR: https://github.com/Kong/go-database-reconciler/pull/267
https://github.com/Kong/deck/issues/1568

tests: add tests for custom entity partial apply

---

Dockerfile
go.mod

This change would also ensure
that we account for CVEs
https://nvd.nist.gov/vuln/detail/cve-2025-22871
and https://nvd.nist.gov/vuln/detail/CVE-2025-22866

chore: updated golang to v1.24.3

---

CHANGELOG.md
README.md

Changes:
deck: https://github.com/Kong/deck/compare/v1.49.0...main
gdr: https://github.com/Kong/go-database-reconciler/compare/v1.24.1...v1.24.2
go-apiops: https://github.com/Kong/go-apiops/compare/v0.1.45...v0.1.46

chore: release prep for v1.49.1

---

cmd/common.go
cmd/gateway_validate.go

The `err` variable was not re-computed, ensuring that it is guaranteed to be non-nil at this point in the code.

chore: remove unused error handling code

---

.github/workflows/integration-enterprise.yaml

This PR adds Kong GW Enterprise v3.11 to the test matrix

chore: add 3.11 to test matrix

---

CHANGELOG.md
README.md

This release will fix the following issues:
https://github.com/Kong/deck/issues/1693
https://github.com/Kong/deck/issues/1620
https://github.com/Kong/deck/issues/1674
https://github.com/Kong/deck/issues/1688
Changes:
deck: https://github.com/Kong/deck/compare/v1.49.1...main
gdr: https://github.com/Kong/go-database-reconciler/compare/v1.24.2...v1.24.3
go-apiops: https://github.com/Kong/go-apiops/compare/v0.1.46...v0.1.47

chore: release prep for v1.49.2

---

CHANGELOG.md
README.md

Changes since last release:
deck: https://github.com/Kong/deck/compare/v1.49.2...main
gdr: https://github.com/Kong/go-database-reconciler/compare/v1.24.3...v1.26.0
go-kong: https://github.com/Kong/go-kong/compare/v0.66.1...v0.67.0
go-apiops: no change

chore: release prep for v1.50.0

---

.github/workflows/release.yaml

go-releaser is taking 10 minutes and timing out before uploading assets. Thus, increasing the timeout period to avoid operation cancellation as it prevents us from releasing the cli.
Approval to increase timeout period: https://kongstrong.slack.com/archives/C027PKSNBC5/p1756369785658399?thread_ts=1756369711.863809&cid=C027PKSNBC5

chore: updated timeout for goreleaser workflow

---

cmd/common.go
go.mod
go.sum
tests/integration/diff_test.go
tests/integration/sync_test.go
tests/integration/test_utils.go
tests/integration/testdata/sync/015-consumer-groups/kong-consumer-1.yaml
tests/integration/testdata/sync/015-consumer-groups/kong-consumer-2.yaml

Syncing and diffing with default_lookup_tags
for consumer-groups was errorneous. While
dumping config, we would dump all consumers
in case of default-lookup tags. Thus, in case of
serial syncing of consumers, previous consumers
would end up getting deleted.
This fix ensures that no unexpected deletions occur
while using consumer-group lookups. 
Issue is described in detail in
the doc and FTI below: 
- [Document](https://konghq.atlassian.net/wiki/spaces/~7120204d7e8997ba384e09b1eee597d986a1dc/pages/4618027031/Default+LookUp+Tags+for+Deck)
- [FTI](https://konghq.atlassian.net/browse/FTI-6754)

fix: consumer lookups while using default lookup tags for consumer-goups

---

go.mod
go.sum

Summary:
- Implements https://github.com/Kong/deck/issues/1702
Related PR: https://github.com/Kong/go-apiops/pull/277

chore: bump go-apiops to v0.2.0

---

CHANGELOG.md
README.md

Changes:
deck: https://github.com/Kong/deck/compare/v1.51.1...main
go-apiops: https://github.com/Kong/go-apiops/compare/v0.1.49...v0.2.0
go-kong: https://github.com/Kong/go-kong/compare/v0.68.0...v0.69.0
gdr: https://github.com/Kong/go-database-reconciler/compare/v1.27.1...v1.28.0

chore: added changelog for v1.52.0
